var lv14Data = [
{ "level": 14, "word": "act", "syllables": ["act"], "ipa": "/ækt/", "meaning": "行動/表演", "sentence": "We must act now to save the environment.", "sentence_cn": "我們必須現在採取行動來保護環境。" },
{ "level": 14, "word": "answer", "syllables": ["an", "swer"], "ipa": "/ˈænsər/", "meaning": "回答", "sentence": "Please answer my question.", "sentence_cn": "請回答我的問題。" },
{ "level": 14, "word": "ask", "syllables": ["ask"], "ipa": "/æsk/", "meaning": "詢問", "sentence": "If you don't know, just ask the teacher.", "sentence_cn": "如果你不知道，就問老師。" },
{ "level": 14, "word": "break", "syllables": ["break"], "ipa": "/breɪk/", "meaning": "打破/休息", "sentence": "Be careful not to break the glass.", "sentence_cn": "小心不要打破玻璃。" },
{ "level": 14, "word": "build", "syllables": ["build"], "ipa": "/bɪld/", "meaning": "建造", "sentence": "They are going to build a new bridge.", "sentence_cn": "他們打算建一座新橋。" },
{ "level": 14, "word": "buy", "syllables": ["buy"], "ipa": "/baɪ/", "meaning": "買", "sentence": "I want to buy a new bicycle.", "sentence_cn": "我想買一輛新腳踏車。" },
{ "level": 14, "word": "call", "syllables": ["call"], "ipa": "/kɔːl/", "meaning": "打電話/呼叫", "sentence": "I will call you later tonight.", "sentence_cn": "我今晚晚點會打給你。" },
{ "level": 14, "word": "camp", "syllables": ["camp"], "ipa": "/kæmp/", "meaning": "露營", "sentence": "We like to camp in the mountains.", "sentence_cn": "我們喜歡在山裡露營。" },
{ "level": 14, "word": "catch", "syllables": ["catch"], "ipa": "/kætʃ/", "meaning": "接住/捕捉", "sentence": "Can you catch the ball?", "sentence_cn": "你能接住球嗎？" },
{ "level": 14, "word": "check", "syllables": ["check"], "ipa": "/tʃek/", "meaning": "檢查", "sentence": "Check your homework before handing it in.", "sentence_cn": "交作業前先檢查一下。" },
{ "level": 14, "word": "clean", "syllables": ["clean"], "ipa": "/kliːn/", "meaning": "打掃/乾淨的", "sentence": "Please clean your room.", "sentence_cn": "請打掃你的房間。" },
{ "level": 14, "word": "climb", "syllables": ["climb"], "ipa": "/klaɪm/", "meaning": "攀爬", "sentence": "The cat can climb the tree easily.", "sentence_cn": "貓可以輕鬆地爬樹。" },
{ "level": 14, "word": "close", "syllables": ["close"], "ipa": "/kloʊz/", "meaning": "關閉", "sentence": "Close the window; it's getting cold.", "sentence_cn": "把窗戶關上，天氣變冷了。" },
{ "level": 14, "word": "come", "syllables": ["come"], "ipa": "/kʌm/", "meaning": "來", "sentence": "Come here and see this.", "sentence_cn": "過來看看這個。" },
{ "level": 14, "word": "cook", "syllables": ["cook"], "ipa": "/kʊk/", "meaning": "烹飪/廚師", "sentence": "My dad likes to cook dinner.", "sentence_cn": "我爸爸喜歡做晚餐。" },
{ "level": 14, "word": "cry", "syllables": ["cry"], "ipa": "/kraɪ/", "meaning": "哭泣", "sentence": "The baby started to cry.", "sentence_cn": "嬰兒開始哭了。" },
{ "level": 14, "word": "cut", "syllables": ["cut"], "ipa": "/kʌt/", "meaning": "剪/切", "sentence": "He cut the paper with scissors.", "sentence_cn": "他用剪刀剪紙。" },
{ "level": 14, "word": "dance", "syllables": ["dance"], "ipa": "/dæns/", "meaning": "跳舞", "sentence": "She loves to dance to the music.", "sentence_cn": "她喜歡隨音樂起舞。" },
{ "level": 14, "word": "dig", "syllables": ["dig"], "ipa": "/dɪɡ/", "meaning": "挖", "sentence": "The dog is trying to dig a hole.", "sentence_cn": "那隻狗正試圖挖一個洞。" },
{ "level": 14, "word": "do", "syllables": ["do"], "ipa": "/duː/", "meaning": "做", "sentence": "What are you going to do today?", "sentence_cn": "你今天打算做什麼？" },
{ "level": 14, "word": "draw", "syllables": ["draw"], "ipa": "/drɔː/", "meaning": "畫", "sentence": "Can you draw a picture for me?", "sentence_cn": "你能幫我畫張畫嗎？" },
{ "level": 14, "word": "drink", "syllables": ["drink"], "ipa": "/drɪŋk/", "meaning": "喝", "sentence": "Drink plenty of water every day.", "sentence_cn": "每天喝充足的水。" },
{ "level": 14, "word": "drive", "syllables": ["drive"], "ipa": "/draɪv/", "meaning": "駕駛", "sentence": "He learned to drive a car.", "sentence_cn": "他學會了開車。" },
{ "level": 14, "word": "eat", "syllables": ["eat"], "ipa": "/iːt/", "meaning": "吃", "sentence": "Don't eat too much junk food.", "sentence_cn": "不要吃太多垃圾食物。" },
{ "level": 14, "word": "feel", "syllables": ["feel"], "ipa": "/fiːl/", "meaning": "感覺", "sentence": "I feel very happy today.", "sentence_cn": "我今天感覺很快樂。" },
{ "level": 14, "word": "fly", "syllables": ["fly"], "ipa": "/flaɪ/", "meaning": "飛/蒼蠅", "sentence": "Birds can fly high in the sky.", "sentence_cn": "鳥可以在天空中高飛。" },
{ "level": 14, "word": "follow", "syllables": ["fol", "low"], "ipa": "/ˈfɑːloʊ/", "meaning": "跟隨", "sentence": "Follow me, and I'll show you the way.", "sentence_cn": "跟我來，我會指引你路。" },
{ "level": 14, "word": "get", "syllables": ["get"], "ipa": "/ɡet/", "meaning": "得到", "sentence": "I need to get some sleep.", "sentence_cn": "我需要睡一會兒。" },
{ "level": 14, "word": "give", "syllables": ["give"], "ipa": "/ɡɪv/", "meaning": "給", "sentence": "Please give me that book.", "sentence_cn": "請把那本書給我。" },
{ "level": 14, "word": "go", "syllables": ["go"], "ipa": "/ɡoʊ/", "meaning": "去", "sentence": "Let's go to the park.", "sentence_cn": "我們去公園吧。" },
{ "level": 14, "word": "help", "syllables": ["help"], "ipa": "/help/", "meaning": "幫助", "sentence": "Can you help me with my bag?", "sentence_cn": "你能幫我提提袋子嗎？" },
{ "level": 14, "word": "hit", "syllables": ["hit"], "ipa": "/hɪt/", "meaning": "打/擊", "sentence": "He hit the ball very hard.", "sentence_cn": "他用力擊球。" },
{ "level": 14, "word": "hold", "syllables": ["hold"], "ipa": "/hoʊld/", "meaning": "拿著/握住", "sentence": "Hold my hand when we cross the road.", "sentence_cn": "過馬路時牽著我的手。" },
{ "level": 14, "word": "hurt", "syllables": ["hurt"], "ipa": "/hɜːrt/", "meaning": "受傷/疼痛", "sentence": "My leg hurts after the race.", "sentence_cn": "賽跑後我的腿很痛。" },
{ "level": 14, "word": "jog", "syllables": ["jog"], "ipa": "/dʒɑːɡ/", "meaning": "慢跑", "sentence": "I jog in the park every morning.", "sentence_cn": "我每天早上在公園慢跑。" },
{ "level": 14, "word": "join", "syllables": ["join"], "ipa": "/dʒɔɪn/", "meaning": "加入", "sentence": "Would you like to join our club?", "sentence_cn": "你想要加入我們的社團嗎？" },
{ "level": 14, "word": "jump", "syllables": ["jump"], "ipa": "/dʒʌmp/", "meaning": "跳躍", "sentence": "The children love to jump on the bed.", "sentence_cn": "孩子們喜歡在床上跳。" },
{ "level": 14, "word": "kick", "syllables": ["kick"], "ipa": "/kɪk/", "meaning": "踢", "sentence": "Don't kick the ball inside the house.", "sentence_cn": "不要在屋內踢球。" },
{ "level": 14, "word": "kiss", "syllables": ["kiss"], "ipa": "/kɪs/", "meaning": "親吻", "sentence": "She gave her mother a kiss.", "sentence_cn": "她親了她媽媽一下。" },
{ "level": 14, "word": "know", "syllables": ["know"], "ipa": "/noʊ/", "meaning": "知道", "sentence": "I know the answer to this question.", "sentence_cn": "我知道這個問題的答案。" },
{ "level": 14, "word": "laugh", "syllables": ["laugh"], "ipa": "/læf/", "meaning": "笑", "sentence": "The movie was so funny, we couldn't stop laughing.", "sentence_cn": "電影太有趣了，我們笑個不停。" },
{ "level": 14, "word": "let", "syllables": ["let"], "ipa": "/let/", "meaning": "讓", "sentence": "Let me help you with that.", "sentence_cn": "讓我來幫你吧。" },
{ "level": 14, "word": "listen", "syllables": ["lis", "ten"], "ipa": "/ˈlɪsn/", "meaning": "聽", "sentence": "Listen to the teacher carefully.", "sentence_cn": "仔細聽老師說話。" },
{ "level": 14, "word": "live", "syllables": ["live"], "ipa": "/lɪv/", "meaning": "居住/生活", "sentence": "Where do you live?", "sentence_cn": "你住在哪裡？" },
{ "level": 14, "word": "look", "syllables": ["look"], "ipa": "/lʊk/", "meaning": "看", "sentence": "Look at the beautiful sunset.", "sentence_cn": "看那美麗的日落。" },
{ "level": 14, "word": "love", "syllables": ["love"], "ipa": "/lʌv/", "meaning": "愛", "sentence": "I love my family.", "sentence_cn": "我愛我的家人。" },
{ "level": 14, "word": "make", "syllables": ["make"], "ipa": "/meɪk/", "meaning": "製作/做", "sentence": "Let's make a cake together.", "sentence_cn": "我們一起做蛋糕吧。" },
{ "level": 14, "word": "meet", "syllables": ["meet"], "ipa": "/miːt/", "meaning": "見面/遇見", "sentence": "Nice to meet you.", "sentence_cn": "很高興見到你。" },
{ "level": 14, "word": "mind", "syllables": ["mind"], "ipa": "/maɪnd/", "meaning": "介意/心智", "sentence": "Do you mind if I open the door?", "sentence_cn": "你介意我開門嗎？" },
{ "level": 14, "word": "paint", "syllables": ["paint"], "ipa": "/peɪnt/", "meaning": "油漆/繪畫", "sentence": "I want to paint my room blue.", "sentence_cn": "我想把房間漆成藍色。" },
{ "level": 14, "word": "pass", "syllables": ["pass"], "ipa": "/pæs/", "meaning": "傳遞/經過/通過", "sentence": "Please pass me the salt.", "sentence_cn": "請把鹽遞給我。" },
{ "level": 14, "word": "pay", "syllables": ["pay"], "ipa": "/peɪ/", "meaning": "支付", "sentence": "I have to pay for the tickets.", "sentence_cn": "我必須付門票錢。" },
{ "level": 14, "word": "plan", "syllables": ["plan"], "ipa": "/plæn/", "meaning": "計畫", "sentence": "We are planning a trip to Japan.", "sentence_cn": "我們正在計畫去日本旅行。" },
{ "level": 14, "word": "play", "syllables": ["play"], "ipa": "/pleɪ/", "meaning": "玩/彈奏/比賽", "sentence": "The kids are playing in the garden.", "sentence_cn": "孩子們在花園裡玩。" },
{ "level": 14, "word": "point", "syllables": ["point"], "ipa": "/pɔɪnt/", "meaning": "指著/點", "sentence": "Don't point at people, it's rude.", "sentence_cn": "不要指著別人，這很不禮貌。" },
{ "level": 14, "word": "pull", "syllables": ["pull"], "ipa": "/pʊl/", "meaning": "拉", "sentence": "Pull the door to open it.", "sentence_cn": "拉開這扇門。" },
{ "level": 14, "word": "push", "syllables": ["push"], "ipa": "/pʊʃ/", "meaning": "推", "sentence": "Push the button to start the machine.", "sentence_cn": "按下按鈕啟動機器。" },
{ "level": 14, "word": "put", "syllables": ["put"], "ipa": "/pʊt/", "meaning": "放", "sentence": "Put your books on the desk.", "sentence_cn": "把書放在書桌上。" },
{ "level": 14, "word": "read", "syllables": ["read"], "ipa": "/riːd/", "meaning": "閱讀", "sentence": "He likes to read books before bed.", "sentence_cn": "他喜歡睡前看書。" },
{ "level": 14, "word": "ride", "syllables": ["ride"], "ipa": "/raɪd/", "meaning": "騎", "sentence": "Can you ride a horse?", "sentence_cn": "你會騎馬嗎？" },
{ "level": 14, "word": "run", "syllables": ["run"], "ipa": "/rʌn/", "meaning": "跑", "sentence": "Run as fast as you can.", "sentence_cn": "盡你所能快跑。" },
{ "level": 14, "word": "say", "syllables": ["say"], "ipa": "/seɪ/", "meaning": "說", "sentence": "What did you say?", "sentence_cn": "你說了什麼？" },
{ "level": 14, "word": "see", "syllables": ["see"], "ipa": "/siː/", "meaning": "看見", "sentence": "I can see the moon from here.", "sentence_cn": "從這裡我可以看到月亮。" },
{ "level": 14, "word": "shine", "syllables": ["shine"], "ipa": "/ʃaɪn/", "meaning": "照耀", "sentence": "The sun is shining brightly.", "sentence_cn": "陽光燦爛照耀。" },
{ "level": 14, "word": "show", "syllables": ["show"], "ipa": "/ʃoʊ/", "meaning": "展示/顯示", "sentence": "Show me your new toy.", "sentence_cn": "給我看你的新玩具。" },
{ "level": 14, "word": "sing", "syllables": ["sing"], "ipa": "/sɪŋ/", "meaning": "唱歌", "sentence": "She sings beautifully.", "sentence_cn": "她唱歌唱得很動聽。" },
{ "level": 14, "word": "sit", "syllables": ["sit"], "ipa": "/sɪt/", "meaning": "坐", "sentence": "Sit down, please.", "sentence_cn": "請坐下。" },
{ "level": 14, "word": "sleep", "syllables": ["sleep"], "ipa": "/sliːp/", "meaning": "睡覺", "sentence": "I didn't sleep well last night.", "sentence_cn": "我昨晚沒睡好。" },
{ "level": 14, "word": "stand", "syllables": ["stand"], "ipa": "/stænd/", "meaning": "站立", "sentence": "Please stand up.", "sentence_cn": "請站起來。" },
{ "level": 14, "word": "start", "syllables": ["start"], "ipa": "/stɑːrt/", "meaning": "開始", "sentence": "The game will start in five minutes.", "sentence_cn": "比賽將在五分鐘後開始。" },
{ "level": 14, "word": "stop", "syllables": ["stop"], "ipa": "/stɑːp/", "meaning": "停止", "sentence": "Stop talking and listen.", "sentence_cn": "停止說話並傾聽。" },
{ "level": 14, "word": "swim", "syllables": ["swim"], "ipa": "/swɪm/", "meaning": "游泳", "sentence": "He can swim across the river.", "sentence_cn": "他能游過那條河。" },
{ "level": 14, "word": "take", "syllables": ["take"], "ipa": "/teɪk/", "meaning": "拿走/搭乘", "sentence": "Take an umbrella with you.", "sentence_cn": "帶把雨傘吧。" },
{ "level": 14, "word": "talk", "syllables": ["talk"], "ipa": "/tɔːk/", "meaning": "說話/談論", "sentence": "We need to talk about it.", "sentence_cn": "我們需要談談這件事。" },
{ "level": 14, "word": "teach", "syllables": ["teach"], "ipa": "/tiːtʃ/", "meaning": "教", "sentence": "She teaches English at school.", "sentence_cn": "她在學校教英文。" },
{ "level": 14, "word": "thank", "syllables": ["thank"], "ipa": "/θæŋk/", "meaning": "感謝", "sentence": "Thank you for your help.", "sentence_cn": "謝謝你的幫助。" },
{ "level": 14, "word": "think", "syllables": ["think"], "ipa": "/θɪŋk/", "meaning": "思考/認為", "sentence": "Let me think about it.", "sentence_cn": "讓我考慮一下。" },
{ "level": 14, "word": "try", "syllables": ["try"], "ipa": "/traɪ/", "meaning": "嘗試", "sentence": "I'll try my best.", "sentence_cn": "我會盡力的。" },
{ "level": 14, "word": "use", "syllables": ["use"], "ipa": "/juːz/", "meaning": "使用", "sentence": "Can I use your pen?", "sentence_cn": "我可以用你的筆嗎？" },
{ "level": 14, "word": "wait", "syllables": ["wait"], "ipa": "/weɪt/", "meaning": "等待", "sentence": "Wait for me at the station.", "sentence_cn": "在車站等我。" },
{ "level": 14, "word": "walk", "syllables": ["walk"], "ipa": "/wɔːk/", "meaning": "走路/散步", "sentence": "I walk to school every day.", "sentence_cn": "我每天走路去上學。" },
{ "level": 14, "word": "want", "syllables": ["want"], "ipa": "/wɑːnt/", "meaning": "想要", "sentence": "I want some water.", "sentence_cn": "我想要一些水。" },
{ "level": 14, "word": "wash", "syllables": ["wash"], "ipa": "/wɔːʃ/", "meaning": "洗", "sentence": "Wash your hands before dinner.", "sentence_cn": "晚餐前洗手。" },
{ "level": 14, "word": "wear", "syllables": ["wear"], "ipa": "/wer/", "meaning": "穿著", "sentence": "I have to wear a uniform to school.", "sentence_cn": "我上學必須穿制服。" },
{ "level": 14, "word": "work", "syllables": ["work"], "ipa": "/wɜːrk/", "meaning": "工作", "sentence": "My parents work very hard.", "sentence_cn": "我的父母工作很努力。" },
{ "level": 14, "word": "write", "syllables": ["write"], "ipa": "/raɪt/", "meaning": "寫", "sentence": "Write your name on the paper.", "sentence_cn": "在紙上寫下你的名字。" }
];