var lv16Data = [
{ "level": 16, "word": "I", "syllables": ["I"], "ipa": "/aɪ/", "meaning": "我", "sentence": "I am a student.", "sentence_cn": "我是一個學生。" },
{ "level": 16, "word": "you", "syllables": ["you"], "ipa": "/juː/", "meaning": "你/你們", "sentence": "You are my best friend.", "sentence_cn": "你是我最好的朋友。" },
{ "level": 16, "word": "he", "syllables": ["he"], "ipa": "/hiː/", "meaning": "他", "sentence": "He is a very tall boy.", "sentence_cn": "他是一個很高大的男孩。" },
{ "level": 16, "word": "she", "syllables": ["she"], "ipa": "/ʃiː/", "meaning": "她", "sentence": "She is reading a book.", "sentence_cn": "她正在讀書。" },
{ "level": 16, "word": "it", "syllables": ["it"], "ipa": "/ɪt/", "meaning": "它/牠", "sentence": "It is a beautiful cat.", "sentence_cn": "它是一隻漂亮的貓。" },
{ "level": 16, "word": "we", "syllables": ["we"], "ipa": "/wiː/", "meaning": "我們", "sentence": "We go to school together.", "sentence_cn": "我們一起去上學。" },
{ "level": 16, "word": "they", "syllables": ["they"], "ipa": "/ðeɪ/", "meaning": "他們/它們", "sentence": "They are playing in the park.", "sentence_cn": "他們正在公園玩耍。" },
{ "level": 16, "word": "who", "syllables": ["who"], "ipa": "/huː/", "meaning": "誰", "sentence": "Who is that man?", "sentence_cn": "那個男人是誰？" },
{ "level": 16, "word": "whose", "syllables": ["whose"], "ipa": "/huːz/", "meaning": "誰的", "sentence": "Whose bag is this?", "sentence_cn": "這是誰的包包？" },
{ "level": 16, "word": "what", "syllables": ["what"], "ipa": "/wɑːt/", "meaning": "什麼", "sentence": "What are you doing?", "sentence_cn": "你在做什麼？" },
{ "level": 16, "word": "where", "syllables": ["where"], "ipa": "/wer/", "meaning": "哪裡", "sentence": "Where do you live?", "sentence_cn": "你住在哪裡？" },
{ "level": 16, "word": "when", "syllables": ["when"], "ipa": "/wen/", "meaning": "何時", "sentence": "When is your birthday?", "sentence_cn": "你的生日是什麼時候？" },
{ "level": 16, "word": "why", "syllables": ["why"], "ipa": "/waɪ/", "meaning": "為什麼", "sentence": "Why are you crying?", "sentence_cn": "你為什麼在哭？" },
{ "level": 16, "word": "how", "syllables": ["how"], "ipa": "/haʊ/", "meaning": "如何/多麼", "sentence": "How are you today?", "sentence_cn": "你今天好嗎？" },
{ "level": 16, "word": "at", "syllables": ["at"], "ipa": "/æt/", "meaning": "在(地點/時間)", "sentence": "I'll see you at school.", "sentence_cn": "我們學校見。" },
{ "level": 16, "word": "back", "syllables": ["back"], "ipa": "/bæk/", "meaning": "後面的/回原處", "sentence": "Please come back soon.", "sentence_cn": "請快點回來。" },
{ "level": 16, "word": "bottom", "syllables": ["bot", "tom"], "ipa": "/ˈbɑːtəm/", "meaning": "底部", "sentence": "The answer is at the bottom of the page.", "sentence_cn": "答案在頁面底部。" },
{ "level": 16, "word": "by", "syllables": ["by"], "ipa": "/baɪ/", "meaning": "在旁邊/藉由", "sentence": "He sits by the window.", "sentence_cn": "他坐在窗戶旁邊。" },
{ "level": 16, "word": "down", "syllables": ["down"], "ipa": "/daʊn/", "meaning": "向下", "sentence": "Sit down, please.", "sentence_cn": "請坐下。" },
{ "level": 16, "word": "from", "syllables": ["from"], "ipa": "/frʌm/", "meaning": "來自", "sentence": "I am from Taiwan.", "sentence_cn": "我來自台灣。" },
{ "level": 16, "word": "front", "syllables": ["front"], "ipa": "/frʌnt/", "meaning": "前面", "sentence": "There is a car in front of the house.", "sentence_cn": "房子前面有一輛車。" },
{ "level": 16, "word": "here", "syllables": ["here"], "ipa": "/hɪr/", "meaning": "這裡", "sentence": "Come here, please.", "sentence_cn": "請過來這裡。" },
{ "level": 16, "word": "in", "syllables": ["in"], "ipa": "/ɪn/", "meaning": "在...裡面", "sentence": "The keys are in the box.", "sentence_cn": "鑰匙在盒子裡。" },
{ "level": 16, "word": "into", "syllables": ["in", "to"], "ipa": "/ˈɪntuː/", "meaning": "進入", "sentence": "He walked into the room.", "sentence_cn": "他走進房間。" },
{ "level": 16, "word": "left", "syllables": ["left"], "ipa": "/left/", "meaning": "左邊", "sentence": "Turn left at the next corner.", "sentence_cn": "在下個轉角左轉。" },
{ "level": 16, "word": "of", "syllables": ["of"], "ipa": "/ʌv/", "meaning": "的", "sentence": "This is a map of the city.", "sentence_cn": "這是這座城市的地圖。" },
{ "level": 16, "word": "off", "syllables": ["off"], "ipa": "/ɔːf/", "meaning": "離開/關閉", "sentence": "Turn off the light, please.", "sentence_cn": "請關燈。" },
{ "level": 16, "word": "on", "syllables": ["on"], "ipa": "/ɑːn/", "meaning": "在...上面", "sentence": "The book is on the table.", "sentence_cn": "書在桌子上。" },
{ "level": 16, "word": "out", "syllables": ["out"], "ipa": "/aʊt/", "meaning": "向外", "sentence": "Let's go out for a walk.", "sentence_cn": "我們出去散步吧。" },
{ "level": 16, "word": "outside", "syllables": ["out", "side"], "ipa": "/ˌaʊtˈsaɪd/", "meaning": "在外面", "sentence": "It is cold outside.", "sentence_cn": "外面很冷。" },
{ "level": 16, "word": "over", "syllables": ["o", "ver"], "ipa": "/ˈoʊvər/", "meaning": "在...上方/超過", "sentence": "The bird flew over the house.", "sentence_cn": "鳥兒飛過房子上方。" },
{ "level": 16, "word": "there", "syllables": ["there"], "ipa": "/ðer/", "meaning": "那裡", "sentence": "Your bag is over there.", "sentence_cn": "你的包包在那裡。" },
{ "level": 16, "word": "under", "syllables": ["un", "der"], "ipa": "/ˈʌndər/", "meaning": "在...下方", "sentence": "The cat is under the chair.", "sentence_cn": "貓在椅子下面。" },
{ "level": 16, "word": "up", "syllables": ["up"], "ipa": "/ʌp/", "meaning": "向上", "sentence": "Stand up, please.", "sentence_cn": "請站起來。" },
{ "level": 16, "word": "and", "syllables": ["and"], "ipa": "/ænd/", "meaning": "和/而且", "sentence": "I like apples and bananas.", "sentence_cn": "我喜歡蘋果和香蕉。" },
{ "level": 16, "word": "also", "syllables": ["al", "so"], "ipa": "/ˈɔːlsoʊ/", "meaning": "也/此外", "sentence": "She is smart and also very kind.", "sentence_cn": "她很聰明，而且也很親切。" },
{ "level": 16, "word": "but", "syllables": ["but"], "ipa": "/bʌt/", "meaning": "但是", "sentence": "I want to go, but I'm busy.", "sentence_cn": "我想去，但是我正忙。" },
{ "level": 16, "word": "if", "syllables": ["if"], "ipa": "/ɪf/", "meaning": "如果", "sentence": "If it rains, we will stay home.", "sentence_cn": "如果下雨，我們就待在家。" },
{ "level": 16, "word": "or", "syllables": ["or"], "ipa": "/ɔːr/", "meaning": "或者", "sentence": "Do you want tea or coffee?", "sentence_cn": "你想要茶還是咖啡？" }
];