var lv7Data = [
{ "level": 7, "word": "time", "syllables": ["time"], "ipa": "/taɪm/", "meaning": "時間", "sentence": "I don't have enough time to finish my homework.", "sentence_cn": "我沒有足夠的時間完成作業。" },
{ "level": 7, "word": "day", "syllables": ["day"], "ipa": "/deɪ/", "meaning": "天/白天", "sentence": "It has been a very long day.", "sentence_cn": "這是非常漫長的一天。" },
{ "level": 7, "word": "today", "syllables": ["to", "day"], "ipa": "/təˈdeɪ/", "meaning": "今天", "sentence": "Today is a beautiful sunny day.", "sentence_cn": "今天是一個晴朗的好日子。" },
{ "level": 7, "word": "week", "syllables": ["week"], "ipa": "/wiːk/", "meaning": "星期/週", "sentence": "There are seven days in a week.", "sentence_cn": "一週有七天。" },
{ "level": 7, "word": "year", "syllables": ["year"], "ipa": "/jɪr/", "meaning": "年", "sentence": "Happy New Year!", "sentence_cn": "新年快樂！" },
{ "level": 7, "word": "morning", "syllables": ["morn", "ing"], "ipa": "/ˈmɔːrnɪŋ/", "meaning": "早晨", "sentence": "I drink milk every morning.", "sentence_cn": "我每天早上喝牛奶。" },
{ "level": 7, "word": "noon", "syllables": ["noon"], "ipa": "/nuːn/", "meaning": "中午", "sentence": "We usually have lunch at noon.", "sentence_cn": "我們通常在中午吃午餐。" },
{ "level": 7, "word": "afternoon", "syllables": ["af", "ter", "noon"], "ipa": "/ˌæftərˈnuːn/", "meaning": "下午", "sentence": "I have a piano lesson this afternoon.", "sentence_cn": "我今天下午有一堂鋼琴課。" },
{ "level": 7, "word": "evening", "syllables": ["eve", "ning"], "ipa": "/ˈiːvnɪŋ/", "meaning": "傍晚/晚上", "sentence": "He watches TV in the evening.", "sentence_cn": "他在晚上看電視。" },
{ "level": 7, "word": "night", "syllables": ["night"], "ipa": "/naɪt/", "meaning": "夜晚", "sentence": "The stars are bright at night.", "sentence_cn": "晚上的星星很亮。" },
{ "level": 7, "word": "o'clock", "syllables": ["o'", "clock"], "ipa": "/əˈklɑːk/", "meaning": "點鐘", "sentence": "It is exactly nine o'clock.", "sentence_cn": "現在正是九點整。" },
{ "level": 7, "word": "date", "syllables": ["date"], "ipa": "/deɪt/", "meaning": "日期", "sentence": "What is the date today?", "sentence_cn": "今天是幾號？" },
{ "level": 7, "word": "Monday", "syllables": ["Mon", "day"], "ipa": "/ˈmʌndeɪ/", "meaning": "星期一", "sentence": "School starts on Monday.", "sentence_cn": "學校在星期一開學。" },
{ "level": 7, "word": "Tuesday", "syllables": ["Tues", "day"], "ipa": "/ˈtuːzdeɪ/", "meaning": "星期二", "sentence": "I go to the gym every Tuesday.", "sentence_cn": "我每個星期二去健身房。" },
{ "level": 7, "word": "Wednesday", "syllables": ["Wednes", "day"], "ipa": "/ˈwenzdeɪ/", "meaning": "星期三", "sentence": "Wednesday is the middle of the week.", "sentence_cn": "星期三是一週的中間。" },
{ "level": 7, "word": "Thursday", "syllables": ["Thurs", "day"], "ipa": "/ˈθɜːrzdeɪ/", "meaning": "星期四", "sentence": "We have music class on Thursday.", "sentence_cn": "我們星期四有音樂課。" },
{ "level": 7, "word": "Friday", "syllables": ["Fri", "day"], "ipa": "/ˈfraɪdeɪ/", "meaning": "星期五", "sentence": "I'm so happy today is Friday.", "sentence_cn": "我很高興今天是星期五。" },
{ "level": 7, "word": "Saturday", "syllables": ["Sat", "ur", "day"], "ipa": "/ˈsætərdeɪ/", "meaning": "星期六", "sentence": "We go to the park on Saturday.", "sentence_cn": "我們星期六去公園。" },
{ "level": 7, "word": "Sunday", "syllables": ["Sun", "day"], "ipa": "/ˈsʌndeɪ/", "meaning": "星期日", "sentence": "Sunday is a rest day for me.", "sentence_cn": "星期日是我的休息日。" },
{ "level": 7, "word": "January", "syllables": ["Jan", "u", "ar", "y"], "ipa": "/ˈdʒænjuˌeri/", "meaning": "一月", "sentence": "January is the first month of the year.", "sentence_cn": "一月是一年的第一個月。" },
{ "level": 7, "word": "February", "syllables": ["Feb", "ru", "ar", "y"], "ipa": "/ˈfebruˌeri/", "meaning": "二月", "sentence": "February is the shortest month.", "sentence_cn": "二月是最短的一個月。" },
{ "level": 7, "word": "March", "syllables": ["March"], "ipa": "/mɑːrtʃ/", "meaning": "三月", "sentence": "Flowers begin to bloom in March.", "sentence_cn": "花朵在三月開始綻放。" },
{ "level": 7, "word": "April", "syllables": ["A", "pril"], "ipa": "/ˈeɪprəl/", "meaning": "四月", "sentence": "April showers bring May flowers.", "sentence_cn": "四月的雨帶來五月的花。" },
{ "level": 7, "word": "May", "syllables": ["May"], "ipa": "/meɪ/", "meaning": "五月", "sentence": "Mother's Day is in May.", "sentence_cn": "母親節在五月。" },
{ "level": 7, "word": "June", "syllables": ["June"], "ipa": "/dʒuːn/", "meaning": "六月", "sentence": "The school year ends in June.", "sentence_cn": "學年於六月結束。" },
{ "level": 7, "word": "July", "syllables": ["Ju", "ly"], "ipa": "/dʒuˈlaɪ/", "meaning": "七月", "sentence": "July is usually very hot.", "sentence_cn": "七月通常非常熱。" },
{ "level": 7, "word": "August", "syllables": ["Au", "gust"], "ipa": "/ˈɔːɡəst/", "meaning": "八月", "sentence": "We go to the beach in August.", "sentence_cn": "我們八月去海邊。" },
{ "level": 7, "word": "September", "syllables": ["Sep", "tem", "ber"], "ipa": "/sepˈtembər/", "meaning": "九月", "sentence": "The new school term starts in September.", "sentence_cn": "新學期在九月開始。" },
{ "level": 7, "word": "October", "syllables": ["Oc", "to", "ber"], "ipa": "/ɑːkˈtoʊbər/", "meaning": "十月", "sentence": "Halloween is on October 31st.", "sentence_cn": "萬聖節在十月三十一日。" },
{ "level": 7, "word": "November", "syllables": ["No", "vem", "ber"], "ipa": "/noʊˈvembər/", "meaning": "十一月", "sentence": "The weather gets cool in November.", "sentence_cn": "十一月天氣變涼了。" },
{ "level": 7, "word": "December", "syllables": ["De", "cem", "ber"], "ipa": "/dɪˈsembər/", "meaning": "十二月", "sentence": "Christmas is in December.", "sentence_cn": "聖誕節在十二月。" }
];