var lv10Data = [
{ "level": 10, "word": "art", "syllables": ["art"], "ipa": "/ɑːrt/", "meaning": "藝術/美術", "sentence": "I like to draw in art class.", "sentence_cn": "我喜歡在美術課畫畫。" },
{ "level": 10, "word": "bag", "syllables": ["bag"], "ipa": "/bæɡ/", "meaning": "袋子/書包", "sentence": "Put your books in your school bag.", "sentence_cn": "把你的書放進書包裡。" },
{ "level": 10, "word": "book", "syllables": ["book"], "ipa": "/bʊk/", "meaning": "書", "sentence": "I am reading an interesting book.", "sentence_cn": "我正在讀一本有趣的書。" },
{ "level": 10, "word": "class", "syllables": ["class"], "ipa": "/klæs/", "meaning": "班級/課堂", "sentence": "There are thirty students in my class.", "sentence_cn": "我們班有三十個學生。" },
{ "level": 10, "word": "desk", "syllables": ["desk"], "ipa": "/desk/", "meaning": "書桌", "sentence": "He sits at his desk and studies.", "sentence_cn": "他在書桌前坐著讀書。" },
{ "level": 10, "word": "glue", "syllables": ["glue"], "ipa": "/ɡluː/", "meaning": "膠水", "sentence": "Use glue to stick the paper together.", "sentence_cn": "用膠水把紙黏在一起。" },
{ "level": 10, "word": "homework", "syllables": ["home", "work"], "ipa": "/ˈhoʊmwɜːrk/", "meaning": "作業", "sentence": "I have a lot of homework tonight.", "sentence_cn": "我今晚有很多作業。" },
{ "level": 10, "word": "lesson", "syllables": ["les", "son"], "ipa": "/ˈlesn/", "meaning": "課/教訓", "sentence": "Today's English lesson was fun.", "sentence_cn": "今天的英文課很有趣。" },
{ "level": 10, "word": "marker", "syllables": ["mark", "er"], "ipa": "/ˈmɑːrkər/", "meaning": "彩色筆/麥克筆", "sentence": "Draw a circle with a red marker.", "sentence_cn": "用紅色麥克筆畫一個圓圈。" },
{ "level": 10, "word": "math", "syllables": ["math"], "ipa": "/mæθ/", "meaning": "數學", "sentence": "Math is my favorite subject.", "sentence_cn": "數學是我最喜歡的科目。" },
{ "level": 10, "word": "note", "syllables": ["note"], "ipa": "/noʊt/", "meaning": "筆記/便條", "sentence": "She wrote a short note to her mother.", "sentence_cn": "她給她媽媽寫了一張短便條。" },
{ "level": 10, "word": "notebook", "syllables": ["note", "book"], "ipa": "/ˈnoʊtbʊk/", "meaning": "筆記本", "sentence": "I take notes in my notebook.", "sentence_cn": "我在筆記本上做筆記。" },
{ "level": 10, "word": "page", "syllables": ["page"], "ipa": "/peɪdʒ/", "meaning": "頁", "sentence": "Open your book to page ten.", "sentence_cn": "把書翻到第十頁。" },
{ "level": 10, "word": "paper", "syllables": ["pa", "per"], "ipa": "/ˈpeɪpər/", "meaning": "紙", "sentence": "Can I have a piece of paper?", "sentence_cn": "可以給我一張紙嗎？" },
{ "level": 10, "word": "PE", "syllables": ["P", "E"], "ipa": "/ˌpiː ˈiː/", "meaning": "體育", "sentence": "We play basketball in PE class.", "sentence_cn": "我們在體育課打籃球。" },
{ "level": 10, "word": "pen", "syllables": ["pen"], "ipa": "/pen/", "meaning": "原子筆", "sentence": "I am writing with a black pen.", "sentence_cn": "我正用一支黑筆寫字。" },
{ "level": 10, "word": "pencil", "syllables": ["pen", "cil"], "ipa": "/ˈpensl/", "meaning": "鉛筆", "sentence": "Please sharpen your pencil.", "sentence_cn": "請削你的鉛筆。" },
{ "level": 10, "word": "quiz", "syllables": ["quiz"], "ipa": "/kwɪz/", "meaning": "小測驗", "sentence": "We have a math quiz every Friday.", "sentence_cn": "我們每個星期五有數學小測驗。" },
{ "level": 10, "word": "ruler", "syllables": ["ru", "ler"], "ipa": "/ˈruːlər/", "meaning": "尺", "sentence": "Use a ruler to draw a straight line.", "sentence_cn": "用尺畫一條直線。" },
{ "level": 10, "word": "story", "syllables": ["sto", "ry"], "ipa": "/ˈstɔːri/", "meaning": "故事", "sentence": "Grandpa told us a funny story.", "sentence_cn": "爺爺給我們講了一個有趣的故事。" },
{ "level": 10, "word": "study", "syllables": ["stud", "y"], "ipa": "/ˈstʌdi/", "meaning": "學習/讀書", "sentence": "He needs to study for the test.", "sentence_cn": "他需要為考試讀書。" },
{ "level": 10, "word": "test", "syllables": ["test"], "ipa": "/test/", "meaning": "考試/測驗", "sentence": "I passed the English test.", "sentence_cn": "我通過了英文考試。" },
{ "level": 10, "word": "word", "syllables": ["word"], "ipa": "/wɜːrd/", "meaning": "單字/話語", "sentence": "I don't know the meaning of this word.", "sentence_cn": "我不知道這個單字的意思。" },
{ "level": 10, "word": "workbook", "syllables": ["work", "book"], "ipa": "/ˈwɜːrkbʊk/", "meaning": "練習本", "sentence": "Finish the exercises in your workbook.", "sentence_cn": "完成練習本裡的練習。" }
];