var lv8Data = [
{ "level": 8, "word": "airport", "syllables": ["air", "port"], "ipa": "/ˈerpɔːrt/", "meaning": "機場", "sentence": "I will meet you at the airport.", "sentence_cn": "我會在機場接你。" },
{ "level": 8, "word": "bank", "syllables": ["bank"], "ipa": "/bæŋk/", "meaning": "銀行", "sentence": "I need to go to the bank to get some money.", "sentence_cn": "我需要去銀行取一些錢。" },
{ "level": 8, "word": "bookstore", "syllables": ["book", "store"], "ipa": "/ˈbʊkstɔːr/", "meaning": "書店", "sentence": "This bookstore has many children's books.", "sentence_cn": "這間書店有很多兒童書。" },
{ "level": 8, "word": "center", "syllables": ["cen", "ter"], "ipa": "/ˈsentər/", "meaning": "中心", "sentence": "There is a big shopping center in the city.", "sentence_cn": "城市裡有一個大型購物中心。" },
{ "level": 8, "word": "church", "syllables": ["church"], "ipa": "/tʃɜːrtʃ/", "meaning": "教堂", "sentence": "They go to church every Sunday morning.", "sentence_cn": "他們每個星期天早上都去教堂。" },
{ "level": 8, "word": "city", "syllables": ["ci", "ty"], "ipa": "/ˈsɪti/", "meaning": "城市", "sentence": "Taipei is a very busy city.", "sentence_cn": "台北是一個非常忙碌的城市。" },
{ "level": 8, "word": "farm", "syllables": ["farm"], "ipa": "/fɑːrm/", "meaning": "農場", "sentence": "My uncle lives on a large farm.", "sentence_cn": "我叔叔住在一個大農場裡。" },
{ "level": 8, "word": "garden", "syllables": ["gar", "den"], "ipa": "/ˈɡɑːrdn/", "meaning": "花園", "sentence": "There are many red roses in the garden.", "sentence_cn": "花園裡有很多紅玫瑰。" },
{ "level": 8, "word": "gym", "syllables": ["gym"], "ipa": "/dʒɪm/", "meaning": "健身房/體育館", "sentence": "He exercises at the gym after work.", "sentence_cn": "他下班後在健身房運動。" },
{ "level": 8, "word": "home", "syllables": ["home"], "ipa": "/hoʊm/", "meaning": "家", "sentence": "It's time to go home and have dinner.", "sentence_cn": "該回家吃晚餐了。" },
{ "level": 8, "word": "house", "syllables": ["house"], "ipa": "/haʊs/", "meaning": "房子/住宅", "sentence": "They live in a beautiful house with a yard.", "sentence_cn": "他們住在一間帶院子的漂亮房子裡。" },
{ "level": 8, "word": "lake", "syllables": ["lake"], "ipa": "/leɪk/", "meaning": "湖泊", "sentence": "Let's go boating on the lake.", "sentence_cn": "我們去湖上划船吧。" },
{ "level": 8, "word": "land", "syllables": ["land"], "ipa": "/lænd/", "meaning": "陸地/土地", "sentence": "The sailors were happy to see land.", "sentence_cn": "水手們很高興看到陸地。" },
{ "level": 8, "word": "library", "syllables": ["li", "brar", "y"], "ipa": "/ˈlaɪbreri/", "meaning": "圖書館", "sentence": "You must be quiet in the library.", "sentence_cn": "在圖書館內必須保持安靜。" },
{ "level": 8, "word": "market", "syllables": ["mar", "ket"], "ipa": "/ˈmɑːrkɪt/", "meaning": "市場", "sentence": "I bought some fresh vegetables at the market.", "sentence_cn": "我在市場買了一些新鮮蔬菜。" },
{ "level": 8, "word": "park", "syllables": ["park"], "ipa": "/pɑːrk/", "meaning": "公園", "sentence": "We often take a walk in the park.", "sentence_cn": "我們經常在公園散步。" },
{ "level": 8, "word": "place", "syllables": ["place"], "ipa": "/pleɪs/", "meaning": "地方", "sentence": "This is a great place for a picnic.", "sentence_cn": "這是一個野餐的好地方。" },
{ "level": 8, "word": "pool", "syllables": ["pool"], "ipa": "/puːl/", "meaning": "水池/游泳池", "sentence": "The children are playing in the swimming pool.", "sentence_cn": "孩子們正在游泳池裡玩耍。" },
{ "level": 8, "word": "post office", "syllables": ["post", "of", "fice"], "ipa": "/ˈpoʊst ˌɑːfɪs/", "meaning": "郵局", "sentence": "Where is the nearest post office?", "sentence_cn": "最近的郵局在哪裡？" },
{ "level": 8, "word": "school", "syllables": ["school"], "ipa": "/skuːl/", "meaning": "學校", "sentence": "My sister goes to school by bus.", "sentence_cn": "我妹妹搭公車去上學。" },
{ "level": 8, "word": "shop", "syllables": ["shop"], "ipa": "/ʃɑːp/", "meaning": "商店", "sentence": "Let's go to the flower shop.", "sentence_cn": "我們去花店吧。" },
{ "level": 8, "word": "store", "syllables": ["store"], "ipa": "/stɔːr/", "meaning": "商店", "sentence": "He works at a grocery store.", "sentence_cn": "他在一家雜貨店工作。" },
{ "level": 8, "word": "supermarket", "syllables": ["su", "per", "mar", "ket"], "ipa": "/ˈsuːpərmɑːrkɪt/", "meaning": "超市", "sentence": "We buy fruit at the supermarket.", "sentence_cn": "我們在超市買水果。" },
{ "level": 8, "word": "zoo", "syllables": ["zoo"], "ipa": "/zuː/", "meaning": "動物園", "sentence": "We saw pandas at the zoo yesterday.", "sentence_cn": "我們昨天在動物園看到了熊貓。" },
{ "level": 8, "word": "bathroom", "syllables": ["bath", "room"], "ipa": "/ˈbæθruːm/", "meaning": "浴室/廁所", "sentence": "The bathroom is at the end of the hall.", "sentence_cn": "浴室在走廊盡頭。" },
{ "level": 8, "word": "bedroom", "syllables": ["bed", "room"], "ipa": "/ˈbedruːm/", "meaning": "臥室", "sentence": "My bedroom has a large window.", "sentence_cn": "我的臥室有一扇大窗戶。" },
{ "level": 8, "word": "dining room", "syllables": ["din", "ing", "room"], "ipa": "/ˈdaɪnɪŋ ruːm/", "meaning": "飯廳", "sentence": "We eat dinner in the dining room.", "sentence_cn": "我們在飯廳吃晚餐。" },
{ "level": 8, "word": "kitchen", "syllables": ["kitch", "en"], "ipa": "/ˈkɪtʃɪn/", "meaning": "廚房", "sentence": "Mom is cooking in the kitchen.", "sentence_cn": "媽媽正在廚房做飯。" },
{ "level": 8, "word": "living room", "syllables": ["liv", "ing", "room"], "ipa": "/ˈlɪvɪŋ ruːm/", "meaning": "客廳", "sentence": "We sit and talk in the living room.", "sentence_cn": "我們在客廳坐著聊天。" },
{ "level": 8, "word": "room", "syllables": ["room"], "ipa": "/ruːm/", "meaning": "房間", "sentence": "Is there a room available in this hotel?", "sentence_cn": "這間飯店還有空房嗎？" },
{ "level": 8, "word": "office", "syllables": ["of", "fice"], "ipa": "/ˈɑːfɪs/", "meaning": "辦公室", "sentence": "The teacher is in her office.", "sentence_cn": "老師在她的辦公室裡。" }
];