var lv2Data = [
{ "level": 2, "word": "zero", "syllables": ["ze", "ro"], "ipa": "/ˈzɪroʊ/", "meaning": "零", "sentence": "The temperature is zero degrees today.", "sentence_cn": "今天的氣溫是零度。" },
{ "level": 2, "word": "one", "syllables": ["one"], "ipa": "/wʌn/", "meaning": "一", "sentence": "I have only one apple left.", "sentence_cn": "我只剩下一個蘋果。" },
{ "level": 2, "word": "two", "syllables": ["two"], "ipa": "/tuː/", "meaning": "二", "sentence": "There are two birds on the branch.", "sentence_cn": "樹枝上有兩隻鳥。" },
{ "level": 2, "word": "three", "syllables": ["three"], "ipa": "/θriː/", "meaning": "三", "sentence": "A triangle has three sides.", "sentence_cn": "三角形有三個邊。" },
{ "level": 2, "word": "four", "syllables": ["four"], "ipa": "/fɔːr/", "meaning": "四", "sentence": "A car has four wheels.", "sentence_cn": "汽車有四個輪子。" },
{ "level": 2, "word": "five", "syllables": ["five"], "ipa": "/faɪv/", "meaning": "五", "sentence": "High five! Give me your hand.", "sentence_cn": "擊掌！給我你的手。" },
{ "level": 2, "word": "six", "syllables": ["six"], "ipa": "/sɪks/", "meaning": "六", "sentence": "He is six years old.", "sentence_cn": "他六歲了。" },
{ "level": 2, "word": "seven", "syllables": ["sev", "en"], "ipa": "/ˈsevən/", "meaning": "七", "sentence": "There are seven days in a week.", "sentence_cn": "一週有七天。" },
{ "level": 2, "word": "eight", "syllables": ["eight"], "ipa": "/eɪt/", "meaning": "八", "sentence": "An octopus has eight legs.", "sentence_cn": "章魚有八條腿。" },
{ "level": 2, "word": "nine", "syllables": ["nine"], "ipa": "/naɪn/", "meaning": "九", "sentence": "The cat has nine lives.", "sentence_cn": "貓有九條命。" },
{ "level": 2, "word": "ten", "syllables": ["ten"], "ipa": "/ten/", "meaning": "十", "sentence": "I have ten fingers on my hands.", "sentence_cn": "我的雙手有十根手指。" },
{ "level": 2, "word": "eleven", "syllables": ["e", "lev", "en"], "ipa": "/ɪˈlevən/", "meaning": "十一", "sentence": "Eleven comes after ten.", "sentence_cn": "十一在十之後。" },
{ "level": 2, "word": "twelve", "syllables": ["twelve"], "ipa": "/twelv/", "meaning": "十二", "sentence": "A dozen is twelve pieces.", "sentence_cn": "一打是十二個。" },
{ "level": 2, "word": "thirteen", "syllables": ["thir", "teen"], "ipa": "/ˌθɜːrˈtiːn/", "meaning": "十三", "sentence": "She is thirteen years old.", "sentence_cn": "她十三歲。" },
{ "level": 2, "word": "fourteen", "syllables": ["four", "teen"], "ipa": "/ˌfɔːrˈtiːn/", "meaning": "十四", "sentence": "There are fourteen students here.", "sentence_cn": "這裡有十四個學生。" },
{ "level": 2, "word": "fifteen", "syllables": ["fif", "teen"], "ipa": "/ˌfɪfˈtiːn/", "meaning": "十五", "sentence": "I will meet you in fifteen minutes.", "sentence_cn": "我十五分鐘後見你。" },
{ "level": 2, "word": "sixteen", "syllables": ["six", "teen"], "ipa": "/ˌsɪkˈstiːn/", "meaning": "十六", "sentence": "Sixteen people joined the game.", "sentence_cn": "十六個人參加了遊戲。" },
{ "level": 2, "word": "seventeen", "syllables": ["sev", "en", "teen"], "ipa": "/ˌsevənˈtiːn/", "meaning": "十七", "sentence": "He has seventeen comic books.", "sentence_cn": "他有十七本漫畫書。" },
{ "level": 2, "word": "eighteen", "syllables": ["eigh", "teen"], "ipa": "/ˌeɪˈtiːn/", "meaning": "十八", "sentence": "You can vote at eighteen.", "sentence_cn": "你十八歲可以投票。" },
{ "level": 2, "word": "nineteen", "syllables": ["nine", "teen"], "ipa": "/ˌnaɪnˈtiːn/", "meaning": "十九", "sentence": "Nineteen is a prime number.", "sentence_cn": "十九是一個質數。" },
{ "level": 2, "word": "twenty", "syllables": ["twen", "ty"], "ipa": "/ˈtwenti/", "meaning": "二十", "sentence": "This book costs twenty dollars.", "sentence_cn": "這本書花費二十美元。" },
{ "level": 2, "word": "thirty", "syllables": ["thir", "ty"], "ipa": "/ˈθɜːrti/", "meaning": "三十", "sentence": "April has thirty days.", "sentence_cn": "四月有三十天。" },
{ "level": 2, "word": "forty", "syllables": ["for", "ty"], "ipa": "/ˈfɔːrti/", "meaning": "四十", "sentence": "Forty people waited in line.", "sentence_cn": "四十個人在排隊。" },
{ "level": 2, "word": "fifty", "syllables": ["fif", "ty"], "ipa": "/ˈfɪfti/", "meaning": "五十", "sentence": "My grandmother is fifty years old.", "sentence_cn": "我的祖母五十歲。" },
{ "level": 2, "word": "sixty", "syllables": ["six", "ty"], "ipa": "/ˈsɪksti/", "meaning": "六十", "sentence": "One hour has sixty minutes.", "sentence_cn": "一小時有六十分鐘。" },
{ "level": 2, "word": "seventy", "syllables": ["sev", "en", "ty"], "ipa": "/ˈsevənti/", "meaning": "七十", "sentence": "There are seventy pages in the book.", "sentence_cn": "書裡有七十頁。" },
{ "level": 2, "word": "eighty", "syllables": ["eigh", "ty"], "ipa": "/ˈeɪti/", "meaning": "八十", "sentence": "My grandfather is eighty.", "sentence_cn": "我爺爺八十歲。" },
{ "level": 2, "word": "ninety", "syllables": ["nine", "ty"], "ipa": "/ˈnaɪnti/", "meaning": "九十", "sentence": "He scored ninety points.", "sentence_cn": "他得了九十分。" },
{ "level": 2, "word": "hundred", "syllables": ["hun", "dred"], "ipa": "/ˈhʌndrəd/", "meaning": "百", "sentence": "I have one hundred dollars.", "sentence_cn": "我有一百美元。" },
{ "level": 2, "word": "thousand", "syllables": ["thou", "sand"], "ipa": "/ˈθaʊznd/", "meaning": "千", "sentence": "A thousand people ran the race.", "sentence_cn": "一千個人參加了比賽。" },
{ "level": 2, "word": "third", "syllables": ["third"], "ipa": "/θɜːrd/", "meaning": "第三/三分之一", "sentence": "He finished the race in third place.", "sentence_cn": "他在比賽中獲得第三名。" },
{ "level": 2, "word": "half", "syllables": ["half"], "ipa": "/hæf/", "meaning": "一半", "sentence": "Please give me half of the cake.", "sentence_cn": "請給我一半的蛋糕。" },
{ "level": 2, "word": "number", "syllables": ["num", "ber"], "ipa": "/ˈnʌmbər/", "meaning": "數字/號碼", "sentence": "What is your phone number?", "sentence_cn": "你的電話號碼是多少？" }
];