var lv12Data = [
{ "level": 12, "word": "air", "syllables": ["air"], "ipa": "/er/", "meaning": "空氣", "sentence": "Fresh air is good for your health.", "sentence_cn": "新鮮空氣對你的健康有益。" },
{ "level": 12, "word": "cloud", "syllables": ["cloud"], "ipa": "/klaʊd/", "meaning": "雲", "sentence": "The sun is behind a white cloud.", "sentence_cn": "太陽在白雲後面。" },
{ "level": 12, "word": "cloudy", "syllables": ["cloud", "y"], "ipa": "/ˈklaʊdi/", "meaning": "多雲的", "sentence": "It is a cloudy day today.", "sentence_cn": "今天是一個多雲的日子。" },
{ "level": 12, "word": "fire", "syllables": ["fire"], "ipa": "/ˈfaɪər/", "meaning": "火", "sentence": "Don't play with fire, it's dangerous.", "sentence_cn": "不要玩火，這很危險。" },
{ "level": 12, "word": "flower", "syllables": ["flow", "er"], "ipa": "/ˈflaʊər/", "meaning": "花", "sentence": "She picked a beautiful flower.", "sentence_cn": "她摘了一朵美麗的花。" },
{ "level": 12, "word": "grass", "syllables": ["grass"], "ipa": "/ɡræs/", "meaning": "草", "sentence": "The cows are eating grass.", "sentence_cn": "母牛正在吃草。" },
{ "level": 12, "word": "hill", "syllables": ["hill"], "ipa": "/hɪl/", "meaning": "小山/丘陵", "sentence": "They ran up the hill.", "sentence_cn": "他們跑上了小山。" },
{ "level": 12, "word": "moon", "syllables": ["moon"], "ipa": "/muːn/", "meaning": "月亮", "sentence": "The moon is very bright tonight.", "sentence_cn": "今晚的月亮很亮。" },
{ "level": 12, "word": "mud", "syllables": ["mud"], "ipa": "/mʌd/", "meaning": "泥巴", "sentence": "My shoes are covered in mud.", "sentence_cn": "我的鞋子沾滿了泥巴。" },
{ "level": 12, "word": "plant", "syllables": ["plant"], "ipa": "/plænt/", "meaning": "植物/種植", "sentence": "I need to water the plants.", "sentence_cn": "我需要給植物澆水。" },
{ "level": 12, "word": "rain", "syllables": ["rain"], "ipa": "/reɪn/", "meaning": "雨", "sentence": "I like the sound of rain.", "sentence_cn": "我喜歡下雨的聲音。" },
{ "level": 12, "word": "rainy", "syllables": ["rain", "y"], "ipa": "/ˈreɪni/", "meaning": "下雨的", "sentence": "Take an umbrella on a rainy day.", "sentence_cn": "下雨天要帶傘。" },
{ "level": 12, "word": "rose", "syllables": ["rose"], "ipa": "/roʊz/", "meaning": "玫瑰", "sentence": "He gave her a red rose.", "sentence_cn": "他送給她一朵紅玫瑰。" },
{ "level": 12, "word": "sky", "syllables": ["sky"], "ipa": "/skaɪ/", "meaning": "天空", "sentence": "The sky is clear and blue.", "sentence_cn": "天空晴朗湛藍。" },
{ "level": 12, "word": "snow", "syllables": ["snow"], "ipa": "/snoʊ/", "meaning": "雪", "sentence": "The children are playing in the snow.", "sentence_cn": "孩子們正在雪地裡玩耍。" },
{ "level": 12, "word": "snowy", "syllables": ["snow", "y"], "ipa": "/ˈsnoʊi/", "meaning": "下雪的", "sentence": "It's a cold and snowy day.", "sentence_cn": "那是一個寒冷且下雪的日子。" },
{ "level": 12, "word": "star", "syllables": ["star"], "ipa": "/stɑːr/", "meaning": "星星", "sentence": "Look at the stars in the sky.", "sentence_cn": "看天空中的星星。" },
{ "level": 12, "word": "sun", "syllables": ["sun"], "ipa": "/sʌn/", "meaning": "太陽", "sentence": "The sun rises in the east.", "sentence_cn": "太陽從東方升起。" },
{ "level": 12, "word": "sunny", "syllables": ["sun", "ny"], "ipa": "/ˈsʌni/", "meaning": "晴朗的", "sentence": "We had a sunny weekend.", "sentence_cn": "我們度過了一個晴朗的週末。" },
{ "level": 12, "word": "tree", "syllables": ["tree"], "ipa": "/triː/", "meaning": "樹", "sentence": "Birds build nests in the tree.", "sentence_cn": "鳥在樹上築巢。" },
{ "level": 12, "word": "weather", "syllables": ["weath", "er"], "ipa": "/ˈweðər/", "meaning": "天氣", "sentence": "What is the weather like today?", "sentence_cn": "今天天氣怎麼樣？" },
{ "level": 12, "word": "wind", "syllables": ["wind"], "ipa": "/wɪnd/", "meaning": "風", "sentence": "The strong wind blew my hat off.", "sentence_cn": "強風吹掉了我的帽子。" },
{ "level": 12, "word": "windy", "syllables": ["wind", "y"], "ipa": "/ˈwɪndi/", "meaning": "有風的", "sentence": "It is too windy to go out.", "sentence_cn": "風太大，不適合出去。" },
{ "level": 12, "word": "spring", "syllables": ["spring"], "ipa": "/sprɪŋ/", "meaning": "春天", "sentence": "Spring is a beautiful season.", "sentence_cn": "春天是一個美麗的季節。" },
{ "level": 12, "word": "summer", "syllables": ["sum", "mer"], "ipa": "/ˈsʌmər/", "meaning": "夏天", "sentence": "It's very hot in the summer.", "sentence_cn": "夏天非常熱。" },
{ "level": 12, "word": "fall", "syllables": ["fall"], "ipa": "/fɔːl/", "meaning": "秋天", "sentence": "Leaves turn yellow in the fall.", "sentence_cn": "秋天時葉子變黃了。" },
{ "level": 12, "word": "winter", "syllables": ["win", "ter"], "ipa": "/ˈwɪntər/", "meaning": "冬天", "sentence": "It often snows here in winter.", "sentence_cn": "這裡冬天經常下雪。" }
];