var lv1Data = [
{ "level": 1, "word": "animal", "syllables": ["an", "i", "mal"], "ipa": "/ˈænɪməl/", "meaning": "動物", "sentence": "A lion is a wild animal.", "sentence_cn": "獅子是野生動物。" },
{ "level": 1, "word": "ant", "syllables": ["ant"], "ipa": "/ænt/", "meaning": "螞蟻", "sentence": "The ant is very small but strong.", "sentence_cn": "螞蟻很小但很有力氣。" },
{ "level": 1, "word": "bee", "syllables": ["bee"], "ipa": "/biː/", "meaning": "蜜蜂", "sentence": "A bee is collecting honey from the flower.", "sentence_cn": "一隻蜜蜂正在花叢中採蜜。" },
{ "level": 1, "word": "bird", "syllables": ["bird"], "ipa": "/bɜːrd/", "meaning": "鳥", "sentence": "The bird is singing in the tree.", "sentence_cn": "鳥兒在樹上唱歌。" },
{ "level": 1, "word": "bug", "syllables": ["bug"], "ipa": "/bʌɡ/", "meaning": "昆蟲/小蟲", "sentence": "There is a bug on the leaf.", "sentence_cn": "葉子上有隻小蟲。" },
{ "level": 1, "word": "butterfly", "syllables": ["but", "ter", "fly"], "ipa": "/ˈbʌtərflaɪ/", "meaning": "蝴蝶", "sentence": "The butterfly has beautiful wings.", "sentence_cn": "蝴蝶有美麗的翅膀。" },
{ "level": 1, "word": "cat", "syllables": ["cat"], "ipa": "/kæt/", "meaning": "貓", "sentence": "My cat likes to sleep on the sofa.", "sentence_cn": "我的貓喜歡睡在沙發上。" },
{ "level": 1, "word": "chicken", "syllables": ["chick", "en"], "ipa": "/ˈtʃɪkɪn/", "meaning": "雞/雞肉", "sentence": "The farmer feeds the chicken every morning.", "sentence_cn": "農夫每天早上餵雞。" },
{ "level": 1, "word": "cow", "syllables": ["cow"], "ipa": "/kaʊ/", "meaning": "母牛", "sentence": "The cow gives us fresh milk.", "sentence_cn": "母牛提供我們新鮮的牛奶。" },
{ "level": 1, "word": "dog", "syllables": ["dog"], "ipa": "/dɔːɡ/", "meaning": "狗", "sentence": "The dog is barking at the stranger.", "sentence_cn": "那隻狗在對陌生人叫。" },
{ "level": 1, "word": "duck", "syllables": ["duck"], "ipa": "/dʌk/", "meaning": "鴨子", "sentence": "The duck is swimming in the pond.", "sentence_cn": "鴨子在池塘裡游泳。" },
{ "level": 1, "word": "elephant", "syllables": ["el", "e", "phant"], "ipa": "/ˈelɪfənt/", "meaning": "大象", "sentence": "An elephant has a very long nose.", "sentence_cn": "大象有很長的鼻子。" },
{ "level": 1, "word": "fish", "syllables": ["fish"], "ipa": "/fɪʃ/", "meaning": "魚", "sentence": "There are many fish in the river.", "sentence_cn": "河裡有很多魚。" },
{ "level": 1, "word": "frog", "syllables": ["frog"], "ipa": "/frɔːɡ/", "meaning": "青蛙", "sentence": "The green frog jumped into the water.", "sentence_cn": "綠色的青蛙跳進了水裡。" },
{ "level": 1, "word": "goat", "syllables": ["goat"], "ipa": "/ɡoʊt/", "meaning": "山羊", "sentence": "The goat is eating grass on the hill.", "sentence_cn": "山羊在山上吃草。" },
{ "level": 1, "word": "hen", "syllables": ["hen"], "ipa": "/hen/", "meaning": "母雞", "sentence": "The hen laid an egg this morning.", "sentence_cn": "母雞今天早上生了一顆蛋。" },
{ "level": 1, "word": "horse", "syllables": ["horse"], "ipa": "/hɔːrs/", "meaning": "馬", "sentence": "He can ride a horse very well.", "sentence_cn": "他馬騎得很好。" },
{ "level": 1, "word": "kangaroo", "syllables": ["kan", "ga", "roo"], "ipa": "/ˌkæŋɡəˈruː/", "meaning": "袋鼠", "sentence": "A kangaroo carries its baby in a pouch.", "sentence_cn": "袋鼠在育兒袋裡帶著小寶寶。" },
{ "level": 1, "word": "lion", "syllables": ["li", "on"], "ipa": "/ˈlaɪən/", "meaning": "獅子", "sentence": "The lion is the king of the forest.", "sentence_cn": "獅子是森林之王。" },
{ "level": 1, "word": "monkey", "syllables": ["mon", "key"], "ipa": "/ˈmʌŋki/", "meaning": "猴子", "sentence": "The monkey is climbing the tree.", "sentence_cn": "猴子正在爬樹。" },
{ "level": 1, "word": "mouse", "syllables": ["mouse"], "ipa": "/maʊs/", "meaning": "老鼠", "sentence": "The cat is chasing a small mouse.", "sentence_cn": "貓正在追一隻小老鼠。" },
{ "level": 1, "word": "pig", "syllables": ["pig"], "ipa": "/pɪɡ/", "meaning": "豬", "sentence": "The pig is playing in the mud.", "sentence_cn": "豬在泥巴裡玩耍。" },
{ "level": 1, "word": "rat", "syllables": ["rat"], "ipa": "/ræt/", "meaning": "大老鼠", "sentence": "A big rat ran across the kitchen floor.", "sentence_cn": "一隻大老鼠跑過廚房地板。" },
{ "level": 1, "word": "sheep", "syllables": ["sheep"], "ipa": "/ʃiːp/", "meaning": "綿羊", "sentence": "The sheep has thick white wool.", "sentence_cn": "綿羊有厚厚的白羊毛。" },
{ "level": 1, "word": "snake", "syllables": ["snake"], "ipa": "/sneɪk/", "meaning": "蛇", "sentence": "Be careful! There is a snake in the grass.", "sentence_cn": "小心！草叢裡有條蛇。" },
{ "level": 1, "word": "spider", "syllables": ["spi", "der"], "ipa": "/ˈspaɪdər/", "meaning": "蜘蛛", "sentence": "The spider is making a web.", "sentence_cn": "蜘蛛正在織網。" },
{ "level": 1, "word": "tiger", "syllables": ["ti", "ger"], "ipa": "/ˈtaɪɡər/", "meaning": "老虎", "sentence": "A tiger has orange fur with black stripes.", "sentence_cn": "老虎有橘色的毛和黑色的條紋。" },
{ "level": 1, "word": "turtle", "syllables": ["tur", "tle"], "ipa": "/ˈtɜːrtl/", "meaning": "烏龜", "sentence": "The turtle moves very slowly.", "sentence_cn": "烏龜移動得很慢。" },
{ "level": 1, "word": "zebra", "syllables": ["ze", "bra"], "ipa": "/ˈziːbrə/", "meaning": "斑馬", "sentence": "A zebra looks like a horse with stripes.", "sentence_cn": "斑馬看起來像是有條紋的馬。" }
];