var lv4Data = [
{ "level": 4, "word": "food", "syllables": ["food"], "ipa": "/fuːd/", "meaning": "食物", "sentence": "We need food to live.", "sentence_cn": "我們需要食物才能生存。" },
{ "level": 4, "word": "apple", "syllables": ["ap", "ple"], "ipa": "/ˈæpl/", "meaning": "蘋果", "sentence": "An apple a day keeps the doctor away.", "sentence_cn": "一日一蘋果，醫生遠離我。" },
{ "level": 4, "word": "banana", "syllables": ["ba", "nan", "a"], "ipa": "/bəˈnænə/", "meaning": "香蕉", "sentence": "The monkey is eating a banana.", "sentence_cn": "猴子正在吃香蕉。" },
{ "level": 4, "word": "bread", "syllables": ["bread"], "ipa": "/bred/", "meaning": "麵包", "sentence": "I usually have bread for breakfast.", "sentence_cn": "我通常早餐吃麵包。" },
{ "level": 4, "word": "butter", "syllables": ["but", "ter"], "ipa": "/ˈbʌtər/", "meaning": "奶油", "sentence": "Spread some butter on the toast.", "sentence_cn": "在吐司上抹一點奶油。" },
{ "level": 4, "word": "cake", "syllables": ["cake"], "ipa": "/keɪk/", "meaning": "蛋糕", "sentence": "We had a big chocolate cake for my birthday.", "sentence_cn": "我生日那天我們吃了一個大的巧克力蛋糕。" },
{ "level": 4, "word": "candy", "syllables": ["can", "dy"], "ipa": "/ˈkændi/", "meaning": "糖果", "sentence": "Too much candy is bad for your teeth.", "sentence_cn": "吃太多糖果對牙齒不好。" },
{ "level": 4, "word": "coffee", "syllables": ["cof", "fee"], "ipa": "/ˈkɔːfi/", "meaning": "咖啡", "sentence": "My father drinks coffee every morning.", "sentence_cn": "我父親每天早上喝咖啡。" },
{ "level": 4, "word": "cookie", "syllables": ["cook", "ie"], "ipa": "/ˈkʊki/", "meaning": "餅乾", "sentence": "Would you like a chocolate chip cookie?", "sentence_cn": "你想要一塊巧克力片餅乾嗎？" },
{ "level": 4, "word": "egg", "syllables": ["egg"], "ipa": "/eɡ/", "meaning": "蛋", "sentence": "I like my eggs fried.", "sentence_cn": "我喜歡吃煎蛋。" },
{ "level": 4, "word": "fruit", "syllables": ["fruit"], "ipa": "/fruːt/", "meaning": "水果", "sentence": "Fresh fruit is good for your health.", "sentence_cn": "新鮮水果對你的健康有益。" },
{ "level": 4, "word": "grape", "syllables": ["grape"], "ipa": "/ɡreɪp/", "meaning": "葡萄", "sentence": "He picked a bunch of grapes.", "sentence_cn": "他摘了一串葡萄。" },
{ "level": 4, "word": "ham", "syllables": ["ham"], "ipa": "/hæm/", "meaning": "火腿", "sentence": "I want a ham and cheese sandwich.", "sentence_cn": "我想要一個火腿起司三明治。" },
{ "level": 4, "word": "hamburger", "syllables": ["ham", "burg", "er"], "ipa": "/ˈhæmbɜːrɡər/", "meaning": "漢堡", "sentence": "Let's go get a hamburger for lunch.", "sentence_cn": "我們午餐去吃漢堡吧。" },
{ "level": 4, "word": "hot dog", "syllables": ["hot", "dog"], "ipa": "/ˈhɑːt ˌdɔːɡ/", "meaning": "熱狗", "sentence": "He put mustard on his hot dog.", "sentence_cn": "他在熱狗上加了芥末。" },
{ "level": 4, "word": "ice", "syllables": ["ice"], "ipa": "/aɪs/", "meaning": "冰", "sentence": "Put some ice in my water, please.", "sentence_cn": "請在我的水裡加點冰。" },
{ "level": 4, "word": "ice cream", "syllables": ["ice", "cream"], "ipa": "/ˌaɪs ˈkriːm/", "meaning": "冰淇淋", "sentence": "I love strawberry ice cream.", "sentence_cn": "我愛草莓冰淇淋。" },
{ "level": 4, "word": "juice", "syllables": ["juice"], "ipa": "/dʒuːs/", "meaning": "果汁", "sentence": "Orange juice has a lot of vitamin C.", "sentence_cn": "柳橙汁含有大量的維生素 C。" },
{ "level": 4, "word": "lemon", "syllables": ["lem", "on"], "ipa": "/ˈlemən/", "meaning": "檸檬", "sentence": "A lemon is very sour.", "sentence_cn": "檸檬非常酸。" },
{ "level": 4, "word": "meat", "syllables": ["meat"], "ipa": "/miːt/", "meaning": "肉", "sentence": "Do you eat meat?", "sentence_cn": "你吃肉嗎？" },
{ "level": 4, "word": "milk", "syllables": ["milk"], "ipa": "/mɪlk/", "meaning": "牛奶", "sentence": "Drink your milk before it gets cold.", "sentence_cn": "趁牛奶變冷前把它喝掉。" },
{ "level": 4, "word": "noodle", "syllables": ["noo", "dle"], "ipa": "/ˈnuːdl/", "meaning": "麵條", "sentence": "She is eating beef noodles.", "sentence_cn": "她正在吃牛肉麵。" },
{ "level": 4, "word": "oil", "syllables": ["oil"], "ipa": "/ɔɪl/", "meaning": "油", "sentence": "We use olive oil for cooking.", "sentence_cn": "我們用橄欖油煮飯。" },
{ "level": 4, "word": "pie", "syllables": ["pie"], "ipa": "/paɪ/", "meaning": "派", "sentence": "My mom made an apple pie.", "sentence_cn": "我媽媽做了一個蘋果派。" },
{ "level": 4, "word": "pizza", "syllables": ["piz", "za"], "ipa": "/ˈpiːtsə/", "meaning": "披薩", "sentence": "Let's order a large pizza.", "sentence_cn": "我們來點一個大披薩吧。" },
{ "level": 4, "word": "pork", "syllables": ["pork"], "ipa": "/pɔːrk/", "meaning": "豬肉", "sentence": "Pork is the most common meat here.", "sentence_cn": "豬肉是這裡最常見的肉類。" },
{ "level": 4, "word": "pumpkin", "syllables": ["pump", "kin"], "ipa": "/ˈpʌmpkɪn/", "meaning": "南瓜", "sentence": "We make pumpkin soup in autumn.", "sentence_cn": "我們在秋天做南瓜湯。" },
{ "level": 4, "word": "rice", "syllables": ["rice"], "ipa": "/raɪs/", "meaning": "米飯", "sentence": "Rice is the main food in many Asian countries.", "sentence_cn": "米飯是許多亞洲國家的主食。" },
{ "level": 4, "word": "salad", "syllables": ["sal", "ad"], "ipa": "/ˈsæləd/", "meaning": "沙拉", "sentence": "I want a garden salad for dinner.", "sentence_cn": "晚餐我想吃一份田園沙拉。" },
{ "level": 4, "word": "sandwich", "syllables": ["sand", "wich"], "ipa": "/ˈsændwɪtʃ/", "meaning": "三明治", "sentence": "He packed a sandwich for his lunch.", "sentence_cn": "他包了一個三明治當午餐。" },
{ "level": 4, "word": "soup", "syllables": ["soup"], "ipa": "/suːp/", "meaning": "湯", "sentence": "The soup is very hot, be careful.", "sentence_cn": "湯很燙，小心。" },
{ "level": 4, "word": "sweet", "syllables": ["sweet"], "ipa": "/swiːt/", "meaning": "甜的/甜點", "sentence": "These grapes are very sweet.", "sentence_cn": "這些葡萄很甜。" },
{ "level": 4, "word": "tea", "syllables": ["tea"], "ipa": "/tiː/", "meaning": "茶", "sentence": "Would you like a cup of tea?", "sentence_cn": "你想要一杯茶嗎？" },
{ "level": 4, "word": "water", "syllables": ["wa", "ter"], "ipa": "/ˈwɔːtər/", "meaning": "水", "sentence": "Please give me a glass of water.", "sentence_cn": "請給我一杯水。" },
{ "level": 4, "word": "yummy", "syllables": ["yum", "my"], "ipa": "/ˈjʌmi/", "meaning": "美味的", "sentence": "This chocolate cake is so yummy!", "sentence_cn": "這個巧克力蛋糕真好吃！" },
{ "level": 4, "word": "breakfast", "syllables": ["break", "fast"], "ipa": "/ˈbrekfəst/", "meaning": "早餐", "sentence": "I have breakfast at seven o'clock.", "sentence_cn": "我七點吃早餐。" },
{ "level": 4, "word": "lunch", "syllables": ["lunch"], "ipa": "/lʌntʃ/", "meaning": "午餐", "sentence": "What did you have for lunch?", "sentence_cn": "你午餐吃了什麼？" },
{ "level": 4, "word": "dinner", "syllables": ["din", "ner"], "ipa": "/ˈdɪnər/", "meaning": "晚餐", "sentence": "We are going out for dinner tonight.", "sentence_cn": "我們今晚要出去吃晚餐。" }
];