var lv15Data = [
{ "level": 15, "word": "angry", "syllables": ["an", "gry"], "ipa": "/ˈæŋɡri/", "meaning": "生氣的", "sentence": "He was angry because I was late.", "sentence_cn": "因為我遲到，他生氣了。" },
{ "level": 15, "word": "bad", "syllables": ["bad"], "ipa": "/bæd/", "meaning": "壞的/差的", "sentence": "The weather today is very bad.", "sentence_cn": "今天的天氣很糟糕。" },
{ "level": 15, "word": "big", "syllables": ["big"], "ipa": "/bɪɡ/", "meaning": "大的", "sentence": "Elephant is a big animal.", "sentence_cn": "大象是大型動物。" },
{ "level": 15, "word": "brave", "syllables": ["brave"], "ipa": "/breɪv/", "meaning": "勇敢的", "sentence": "The brave boy saved the cat from the tree.", "sentence_cn": "那個勇敢的男孩從樹上救下了貓。" },
{ "level": 15, "word": "busy", "syllables": ["bus", "y"], "ipa": "/ˈbɪzi/", "meaning": "忙碌的", "sentence": "My mother is always busy on Mondays.", "sentence_cn": "我媽媽星期一總是很忙。" },
{ "level": 15, "word": "careful", "syllables": ["care", "ful"], "ipa": "/ˈkerfl/", "meaning": "小心的", "sentence": "Be careful with that glass vase.", "sentence_cn": "拿那個玻璃花瓶要小心。" },
{ "level": 15, "word": "clear", "syllables": ["clear"], "ipa": "/klɪr/", "meaning": "清楚的/晴朗的", "sentence": "The sky is clear and blue today.", "sentence_cn": "今天天空晴朗湛藍。" },
{ "level": 15, "word": "cold", "syllables": ["cold"], "ipa": "/koʊld/", "meaning": "冷的", "sentence": "It is very cold in winter.", "sentence_cn": "冬天非常冷。" },
{ "level": 15, "word": "cool", "syllables": ["cool"], "ipa": "/kuːl/", "meaning": "涼爽的/酷的", "sentence": "The breeze feels so cool.", "sentence_cn": "微風感覺非常涼爽。" },
{ "level": 15, "word": "cute", "syllables": ["cute"], "ipa": "/kjuːt/", "meaning": "可愛的", "sentence": "Your puppy is so cute!", "sentence_cn": "你的小狗真可愛！" },
{ "level": 15, "word": "dear", "syllables": ["dear"], "ipa": "/dɪr/", "meaning": "親愛的", "sentence": "Dear John, how are you?", "sentence_cn": "親愛的約翰，你好嗎？" },
{ "level": 15, "word": "deep", "syllables": ["deep"], "ipa": "/diːp/", "meaning": "深的", "sentence": "The water in the river is very deep.", "sentence_cn": "這條河的水很深。" },
{ "level": 15, "word": "dirty", "syllables": ["dir", "ty"], "ipa": "/ˈdɜːrti/", "meaning": "髒的", "sentence": "Your hands are dirty; go wash them.", "sentence_cn": "你的手很髒，去洗一下。" },
{ "level": 15, "word": "dry", "syllables": ["dry"], "ipa": "/draɪ/", "meaning": "乾的", "sentence": "Is the laundry dry yet?", "sentence_cn": "衣服曬乾了嗎？" },
{ "level": 15, "word": "easy", "syllables": ["ea", "sy"], "ipa": "/ˈiːzi/", "meaning": "容易的", "sentence": "The math test was very easy.", "sentence_cn": "數學考試非常簡單。" },
{ "level": 15, "word": "far", "syllables": ["far"], "ipa": "/fɑːr/", "meaning": "遠的", "sentence": "The school is not far from my house.", "sentence_cn": "學校離我家不遠。" },
{ "level": 15, "word": "fast", "syllables": ["fast"], "ipa": "/fæst/", "meaning": "快的", "sentence": "He can run very fast.", "sentence_cn": "他可以跑得很快。" },
{ "level": 15, "word": "fat", "syllables": ["fat"], "ipa": "/fæt/", "meaning": "胖的", "sentence": "The cat is getting a little fat.", "sentence_cn": "這隻貓變胖了一點。" },
{ "level": 15, "word": "free", "syllables": ["free"], "ipa": "/friː/", "meaning": "免費的/自由的/空閒的", "sentence": "Are you free this weekend?", "sentence_cn": "你這週末有空嗎？" },
{ "level": 15, "word": "friendly", "syllables": ["friend", "ly"], "ipa": "/ˈfrendli/", "meaning": "友善的", "sentence": "The people here are very friendly.", "sentence_cn": "這裡的人非常友善。" },
{ "level": 15, "word": "full", "syllables": ["full"], "ipa": "/fʊl/", "meaning": "滿的/飽的", "sentence": "The glass is full of milk.", "sentence_cn": "玻璃杯裝滿了牛奶。" },
{ "level": 15, "word": "funny", "syllables": ["fun", "ny"], "ipa": "/ˈfʌni/", "meaning": "好笑的/滑稽的", "sentence": "The clown is very funny.", "sentence_cn": "那個小丑非常滑稽。" },
{ "level": 15, "word": "good", "syllables": ["good"], "ipa": "/ɡʊd/", "meaning": "好的", "sentence": "Have a good day!", "sentence_cn": "祝你有美好的一天！" },
{ "level": 15, "word": "great", "syllables": ["great"], "ipa": "/ɡreɪt/", "meaning": "棒的/偉大的", "sentence": "You did a great job!", "sentence_cn": "你做得很棒！" },
{ "level": 15, "word": "happy", "syllables": ["hap", "py"], "ipa": "/ˈhæpi/", "meaning": "快樂的", "sentence": "I am so happy to see you.", "sentence_cn": "見到你我很高興。" },
{ "level": 15, "word": "hard", "syllables": ["hard"], "ipa": "/hɑːrd/", "meaning": "硬的/困難的/努力的", "sentence": "The rock is very hard.", "sentence_cn": "這石頭非常硬。" },
{ "level": 15, "word": "high", "syllables": ["high"], "ipa": "/haɪ/", "meaning": "高的", "sentence": "The plane is flying very high.", "sentence_cn": "飛機飛得很高。" },
{ "level": 15, "word": "hot", "syllables": ["hot"], "ipa": "/hɑːt/", "meaning": "熱的", "sentence": "The soup is very hot.", "sentence_cn": "湯很燙。" },
{ "level": 15, "word": "hungry", "syllables": ["hun", "gry"], "ipa": "/ˈhʌŋɡri/", "meaning": "飢餓的", "sentence": "I am so hungry; let's eat.", "sentence_cn": "我好餓，我們吃飯吧。" },
{ "level": 15, "word": "large", "syllables": ["large"], "ipa": "/lɑːrdʒ/", "meaning": "巨大的/大的", "sentence": "They live in a large house.", "sentence_cn": "他們住在一間大房子裡。" },
{ "level": 15, "word": "late", "syllables": ["late"], "ipa": "/leɪt/", "meaning": "遲的/晚的", "sentence": "Hurry up, or we will be late.", "sentence_cn": "快點，否則我們會遲到。" },
{ "level": 15, "word": "lazy", "syllables": ["la", "zy"], "ipa": "/ˈleɪzi/", "meaning": "懶惰的", "sentence": "Don't be so lazy; go and study.", "sentence_cn": "別這麼懶，去讀書。" },
{ "level": 15, "word": "little", "syllables": ["lit", "tle"], "ipa": "/ˈlɪtl/", "meaning": "小的/一點點", "sentence": "Give me a little water, please.", "sentence_cn": "請給我一點點水。" },
{ "level": 15, "word": "long", "syllables": ["long"], "ipa": "/lɔːŋ/", "meaning": "長的", "sentence": "She has very long hair.", "sentence_cn": "她的頭髮很長。" },
{ "level": 15, "word": "low", "syllables": ["low"], "ipa": "/loʊ/", "meaning": "低的", "sentence": "The ceiling is quite low.", "sentence_cn": "天花板相當低。" },
{ "level": 15, "word": "lucky", "syllables": ["luck", "y"], "ipa": "/ˈlʌki/", "meaning": "幸運的", "sentence": "You are very lucky to win the game.", "sentence_cn": "你很幸運能贏得這場比賽。" },
{ "level": 15, "word": "mad", "syllables": ["mad"], "ipa": "/mæd/", "meaning": "瘋狂的/生氣的", "sentence": "Dad was mad at me for breaking the window.", "sentence_cn": "爸爸因為我打破窗戶而對我生氣。" },
{ "level": 15, "word": "many", "syllables": ["man", "y"], "ipa": "/ˈmeni/", "meaning": "許多的", "sentence": "There are many flowers in the park.", "sentence_cn": "公園裡有許多花。" },
{ "level": 15, "word": "more", "syllables": ["more"], "ipa": "/mɔːr/", "meaning": "更多的", "sentence": "I need some more time.", "sentence_cn": "我需要更多時間。" },
{ "level": 15, "word": "much", "syllables": ["much"], "ipa": "/mʌtʃ/", "meaning": "大量的/許多的", "sentence": "Thank you very much.", "sentence_cn": "非常感謝你。" },
{ "level": 15, "word": "near", "syllables": ["near"], "ipa": "/nɪr/", "meaning": "近的", "sentence": "Is there a convenience store near here?", "sentence_cn": "這附近有便利商店嗎？" },
{ "level": 15, "word": "nervous", "syllables": ["ner", "vous"], "ipa": "/ˈnɜːrvəs/", "meaning": "緊張的", "sentence": "I feel nervous about the test.", "sentence_cn": "我對這次考試感到緊張。" },
{ "level": 15, "word": "new", "syllables": ["new"], "ipa": "/nuː/", "meaning": "新的", "sentence": "I bought a new pair of shoes.", "sentence_cn": "我買了一雙新鞋。" },
{ "level": 15, "word": "nice", "syllables": ["nice"], "ipa": "/naɪs/", "meaning": "好的/漂亮的", "sentence": "Have a nice weekend!", "sentence_cn": "祝你有個美好的週末！" },
{ "level": 15, "word": "old", "syllables": ["old"], "ipa": "/oʊld/", "meaning": "老的/舊的", "sentence": "My grandfather is eighty years old.", "sentence_cn": "我爺爺八十歲了。" },
{ "level": 15, "word": "pretty", "syllables": ["pret", "ty"], "ipa": "/ˈprɪti/", "meaning": "漂亮的/相當地", "sentence": "She is wearing a pretty dress.", "sentence_cn": "她穿著一件漂亮的洋裝。" },
{ "level": 15, "word": "ready", "syllables": ["read", "y"], "ipa": "/ˈredi/", "meaning": "準備好的", "sentence": "Are you ready to go?", "sentence_cn": "你準備好要出發了嗎？" },
{ "level": 15, "word": "right", "syllables": ["right"], "ipa": "/raɪt/", "meaning": "正確的/右邊的/權利", "sentence": "You are absolutely right.", "sentence_cn": "你是完全正確的。" },
{ "level": 15, "word": "round", "syllables": ["round"], "ipa": "/raʊnd/", "meaning": "圓形的", "sentence": "The earth is round.", "sentence_cn": "地球是圓的。" },
{ "level": 15, "word": "sad", "syllables": ["sad"], "ipa": "/sæd/", "meaning": "傷心的", "sentence": "He was very sad when his cat died.", "sentence_cn": "當他的貓過世時他非常傷心。" },
{ "level": 15, "word": "short", "syllables": ["short"], "ipa": "/ʃɔːrt/", "meaning": "短的/矮的", "sentence": "The pencil is too short to use.", "sentence_cn": "這支鉛筆太短了，無法使用。" },
{ "level": 15, "word": "sick", "syllables": ["sick"], "ipa": "/sɪk/", "meaning": "生病的", "sentence": "He is sick and stays in bed.", "sentence_cn": "他病了，躺在床上休息。" },
{ "level": 15, "word": "slow", "syllables": ["slow"], "ipa": "/sloʊ/", "meaning": "慢的", "sentence": "Please speak more slow so I can understand.", "sentence_cn": "請說慢一點，我才能聽懂。" },
{ "level": 15, "word": "small", "syllables": ["small"], "ipa": "/smɔːl/", "meaning": "小的", "sentence": "The house is very small but cozy.", "sentence_cn": "這房子很小但很溫馨。" },
{ "level": 15, "word": "sorry", "syllables": ["sor", "ry"], "ipa": "/ˈsɔːri/", "meaning": "抱歉的/遺憾的", "sentence": "I'm sorry, I forgot your name.", "sentence_cn": "對不起，我忘了你的名字。" },
{ "level": 15, "word": "surprised", "syllables": ["sur", "prised"], "ipa": "/sərˈpraɪzd/", "meaning": "驚訝的", "sentence": "I was surprised by the news.", "sentence_cn": "我被這則新聞驚嚇到了。" },
{ "level": 15, "word": "tall", "syllables": ["tall"], "ipa": "/tɔːl/", "meaning": "高的", "sentence": "He is the tallest boy in our class.", "sentence_cn": "他是我們班最高的男生。" },
{ "level": 15, "word": "thin", "syllables": ["thin"], "ipa": "/θɪn/", "meaning": "瘦的/薄的", "sentence": "He is tall and thin.", "sentence_cn": "他長得又高又瘦。" },
{ "level": 15, "word": "tired", "syllables": ["tired"], "ipa": "/ˈtaɪərd/", "meaning": "疲倦的", "sentence": "I'm so tired after work.", "sentence_cn": "下班後我好累。" },
{ "level": 15, "word": "true", "syllables": ["true"], "ipa": "/truː/", "meaning": "真實的", "sentence": "Is it true that you are moving?", "sentence_cn": "你要搬家是真的嗎？" },
{ "level": 15, "word": "ugly", "syllables": ["ug", "ly"], "ipa": "/ˈʌɡli/", "meaning": "醜的", "sentence": "The monster in the story is ugly.", "sentence_cn": "故事裡的怪物很醜。" },
{ "level": 15, "word": "unhappy", "syllables": ["un", "hap", "py"], "ipa": "/ʌnˈhæpi/", "meaning": "不快樂的", "sentence": "She was unhappy with the results.", "sentence_cn": "她對結果不滿意。" },
{ "level": 15, "word": "warm", "syllables": ["warm"], "ipa": "/wɔːrm/", "meaning": "溫暖的", "sentence": "The weather is nice and warm today.", "sentence_cn": "今天天氣很好而且很溫暖。" },
{ "level": 15, "word": "wrong", "syllables": ["wrong"], "ipa": "/rɔːŋ/", "meaning": "錯誤的", "sentence": "I answered the question wrong.", "sentence_cn": "我回答錯了這個問題。" },
{ "level": 15, "word": "young", "syllables": ["young"], "ipa": "/jʌŋ/", "meaning": "年輕的", "sentence": "When I was young, I lived in the countryside.", "sentence_cn": "當我年輕的時候，我住在鄉下。" }
];