var lv13Data = [
{ "level": 13, "word": "basket", "syllables": ["bas", "ket"], "ipa": "/ˈbæskɪt/", "meaning": "籃子", "sentence": "Put the apples in the basket.", "sentence_cn": "把蘋果放進籃子裡。" },
{ "level": 13, "word": "bat", "syllables": ["bat"], "ipa": "/bæt/", "meaning": "球棒/蝙蝠", "sentence": "He hit the ball with a wooden bat.", "sentence_cn": "他用木棒擊球。" },
{ "level": 13, "word": "bed", "syllables": ["bed"], "ipa": "/bed/", "meaning": "床", "sentence": "It is time to go to bed.", "sentence_cn": "該上床睡覺了。" },
{ "level": 13, "word": "bell", "syllables": ["bell"], "ipa": "/bel/", "meaning": "鈴鐺/鐘", "sentence": "The school bell is ringing.", "sentence_cn": "校鈴正在響。" },
{ "level": 13, "word": "bowl", "syllables": ["bowl"], "ipa": "/boʊl/", "meaning": "碗", "sentence": "I ate a bowl of rice for lunch.", "sentence_cn": "我午餐吃了一碗飯。" },
{ "level": 13, "word": "box", "syllables": ["box"], "ipa": "/bɑːks/", "meaning": "盒子/箱子", "sentence": "What is inside that big box?", "sentence_cn": "那個大盒子裡裝了什麼？" },
{ "level": 13, "word": "card", "syllables": ["card"], "ipa": "/kɑːrd/", "meaning": "卡片", "sentence": "She sent me a birthday card.", "sentence_cn": "她寄給我一張生日卡片。" },
{ "level": 13, "word": "case", "syllables": ["case"], "ipa": "/keɪs/", "meaning": "盒子/盒/箱", "sentence": "I keep my glasses in a hard case.", "sentence_cn": "我把眼鏡放在硬盒裡。" },
{ "level": 13, "word": "chair", "syllables": ["chair"], "ipa": "/tʃer/", "meaning": "椅子", "sentence": "Please sit down on the chair.", "sentence_cn": "請坐在椅子上。" },
{ "level": 13, "word": "clock", "syllables": ["clock"], "ipa": "/klɑːk/", "meaning": "時鐘", "sentence": "The clock on the wall is slow.", "sentence_cn": "牆上的時鐘慢了。" },
{ "level": 13, "word": "cup", "syllables": ["cup"], "ipa": "/kʌp/", "meaning": "杯子", "sentence": "Would you like a cup of tea?", "sentence_cn": "你想要一杯茶嗎？" },
{ "level": 13, "word": "dish", "syllables": ["dish"], "ipa": "/dɪʃ/", "meaning": "盤子/菜餚", "sentence": "I helped my mom wash the dishes.", "sentence_cn": "我幫媽媽洗盤子。" },
{ "level": 13, "word": "doll", "syllables": ["doll"], "ipa": "/dɑːl/", "meaning": "洋娃娃", "sentence": "The little girl is playing with her doll.", "sentence_cn": "小女孩正在玩她的洋娃娃。" },
{ "level": 13, "word": "door", "syllables": ["door"], "ipa": "/dɔːr/", "meaning": "門", "sentence": "Please close the door behind you.", "sentence_cn": "請隨手關門。" },
{ "level": 13, "word": "fan", "syllables": ["fan"], "ipa": "/fæn/", "meaning": "風扇/迷", "sentence": "Turn on the fan; it's hot in here.", "sentence_cn": "打開電風扇，這裡很熱。" },
{ "level": 13, "word": "file", "syllables": ["file"], "ipa": "/faɪl/", "meaning": "文件夾/檔案", "sentence": "I organized the papers in a file.", "sentence_cn": "我把文件整理在文件夾裡。" },
{ "level": 13, "word": "fork", "syllables": ["fork"], "ipa": "/fɔːrk/", "meaning": "叉子", "sentence": "We use a knife and fork to eat steak.", "sentence_cn": "我們用刀叉吃牛排。" },
{ "level": 13, "word": "gift", "syllables": ["gift"], "ipa": "/ɡɪft/", "meaning": "禮物", "sentence": "I bought a gift for my teacher.", "sentence_cn": "我給老師買了一份禮物。" },
{ "level": 13, "word": "glass", "syllables": ["glass"], "ipa": "/ɡlæs/", "meaning": "玻璃杯/玻璃", "sentence": "May I have a glass of water?", "sentence_cn": "可以給我一杯水嗎？" },
{ "level": 13, "word": "key", "syllables": ["key"], "ipa": "/kiː/", "meaning": "鑰匙", "sentence": "I can't find my house key.", "sentence_cn": "我找不到家裡的鑰匙。" },
{ "level": 13, "word": "kite", "syllables": ["kite"], "ipa": "/kaɪt/", "meaning": "風箏", "sentence": "Let's fly a kite in the park.", "sentence_cn": "我們去公園放風箏吧。" },
{ "level": 13, "word": "lamp", "syllables": ["lamp"], "ipa": "/læmp/", "meaning": "燈", "sentence": "Turn off the lamp before you sleep.", "sentence_cn": "睡覺前請關燈。" },
{ "level": 13, "word": "mop", "syllables": ["mop"], "ipa": "/mɑːp/", "meaning": "拖把", "sentence": "Use a mop to clean the floor.", "sentence_cn": "用拖把清理地板。" },
{ "level": 13, "word": "photo", "syllables": ["pho", "to"], "ipa": "/ˈfoʊtoʊ/", "meaning": "照片", "sentence": "He showed me a photo of his family.", "sentence_cn": "他給我看了一張他家人的照片。" },
{ "level": 13, "word": "piano", "syllables": ["pi", "an", "o"], "ipa": "/piˈænoʊ/", "meaning": "鋼琴", "sentence": "She practices the piano every day.", "sentence_cn": "她每天練習鋼琴。" },
{ "level": 13, "word": "picture", "syllables": ["pic", "ture"], "ipa": "/ˈpɪktʃər/", "meaning": "圖片/畫", "sentence": "Draw a picture of a house.", "sentence_cn": "畫一張房子的畫。" },
{ "level": 13, "word": "pot", "syllables": ["pot"], "ipa": "/pɑːt/", "meaning": "鍋子", "sentence": "The soup is boiling in the pot.", "sentence_cn": "湯正在鍋裡沸騰。" },
{ "level": 13, "word": "robot", "syllables": ["ro", "bot"], "ipa": "/ˈroʊbɑːt/", "meaning": "機器人", "sentence": "The robot can clean the house.", "sentence_cn": "機器人會打掃房子。" },
{ "level": 13, "word": "table", "syllables": ["ta", "ble"], "ipa": "/ˈteɪbl/", "meaning": "桌子", "sentence": "Dinner is ready on the table.", "sentence_cn": "晚餐在桌上準備好了。" },
{ "level": 13, "word": "tool", "syllables": ["tool"], "ipa": "/tuːl/", "meaning": "工具", "sentence": "A hammer is a useful tool.", "sentence_cn": "鐵鎚是很有用的工具。" },
{ "level": 13, "word": "toy", "syllables": ["toy"], "ipa": "/tɔɪ/", "meaning": "玩具", "sentence": "The boy loves his new toy.", "sentence_cn": "那個男孩很喜歡他的新玩具。" },
{ "level": 13, "word": "watch", "syllables": ["watch"], "ipa": "/wɑːtʃ/", "meaning": "手錶/觀看", "sentence": "My watch stopped working.", "sentence_cn": "我的手錶壞了。" },
{ "level": 13, "word": "window", "syllables": ["win", "dow"], "ipa": "/ˈwɪndoʊ/", "meaning": "窗戶", "sentence": "Please open the window for some fresh air.", "sentence_cn": "請打開窗戶讓空氣流通。" }
];