var lv5Data = [
{ "level": 5, "word": "baby", "syllables": ["ba", "by"], "ipa": "/ˈbeɪbi/", "meaning": "嬰兒", "sentence": "The baby is sleeping in the crib.", "sentence_cn": "嬰兒正在嬰兒床裡睡覺。" },
{ "level": 5, "word": "boy", "syllables": ["boy"], "ipa": "/bɔɪ/", "meaning": "男孩", "sentence": "The little boy is playing with his toy car.", "sentence_cn": "小男孩正在玩他的玩具車。" },
{ "level": 5, "word": "brother", "syllables": ["broth", "er"], "ipa": "/ˈbrʌðər/", "meaning": "兄弟", "sentence": "My older brother is a college student.", "sentence_cn": "我的哥哥是個大學生。" },
{ "level": 5, "word": "child", "syllables": ["child"], "ipa": "/tʃaɪld/", "meaning": "小孩", "sentence": "The child is drawing a picture.", "sentence_cn": "小孩正在畫畫。" },
{ "level": 5, "word": "doctor", "syllables": ["doc", "tor"], "ipa": "/ˈdɑːktər/", "meaning": "醫生", "sentence": "The doctor is checking the patient.", "sentence_cn": "醫生正在檢查病人。" },
{ "level": 5, "word": "driver", "syllables": ["dri", "ver"], "ipa": "/ˈdraɪvər/", "meaning": "司機", "sentence": "Our bus driver is very friendly.", "sentence_cn": "我們的公車司機非常友善。" },
{ "level": 5, "word": "farmer", "syllables": ["far", "mer"], "ipa": "/ˈfɑːrmər/", "meaning": "農夫", "sentence": "The farmer grows rice on his farm.", "sentence_cn": "農夫在農場裡種植稻米。" },
{ "level": 5, "word": "father", "syllables": ["fa", "ther"], "ipa": "/ˈfɑːðər/", "meaning": "父親", "sentence": "My father works in a big office.", "sentence_cn": "我的父親在一間大辦公室工作。" },
{ "level": 5, "word": "friend", "syllables": ["friend"], "ipa": "/frend/", "meaning": "朋友", "sentence": "She is my best friend at school.", "sentence_cn": "她是我在學校最好的朋友。" },
{ "level": 5, "word": "girl", "syllables": ["girl"], "ipa": "/ɡɜːrl/", "meaning": "女孩", "sentence": "The girl is wearing a beautiful dress.", "sentence_cn": "那個女孩穿著一件漂亮的洋裝。" },
{ "level": 5, "word": "grandfather", "syllables": ["grand", "fa", "ther"], "ipa": "/ˈɡrændfɑːðər/", "meaning": "祖父/外祖父", "sentence": "My grandfather tells great stories.", "sentence_cn": "我的祖父很會講故事。" },
{ "level": 5, "word": "grandmother", "syllables": ["grand", "moth", "er"], "ipa": "/ˈɡrændmʌðər/", "meaning": "祖母/外祖母", "sentence": "My grandmother likes to bake cookies.", "sentence_cn": "我的祖母喜歡烤餅乾。" },
{ "level": 5, "word": "kid", "syllables": ["kid"], "ipa": "/kɪd/", "meaning": "小孩", "sentence": "The kids are playing in the park.", "sentence_cn": "孩子們正在公園裡玩耍。" },
{ "level": 5, "word": "king", "syllables": ["king"], "ipa": "/kɪŋ/", "meaning": "國王", "sentence": "The king lives in a large castle.", "sentence_cn": "國王住在一座巨大的城堡裡。" },
{ "level": 5, "word": "man", "syllables": ["man"], "ipa": "/mæn/", "meaning": "男人", "sentence": "The man is walking his dog.", "sentence_cn": "那個男人正在遛狗。" },
{ "level": 5, "word": "Miss", "syllables": ["Miss"], "ipa": "/mɪs/", "meaning": "小姐(未婚)", "sentence": "Miss White is our new English teacher.", "sentence_cn": "懷特小姐是我們的新英文老師。" },
{ "level": 5, "word": "mother", "syllables": ["moth", "er"], "ipa": "/ˈmʌðər/", "meaning": "母親", "sentence": "My mother is a very good cook.", "sentence_cn": "我的母親是一位很好的廚師。" },
{ "level": 5, "word": "Mr.", "syllables": ["Mr."], "ipa": "/ˈmɪstər/", "meaning": "先生", "sentence": "Mr. Wang is a hard-working man.", "sentence_cn": "王先生是個勤奮的人。" },
{ "level": 5, "word": "Mrs.", "syllables": ["Mrs."], "ipa": "/ˈmɪsɪz/", "meaning": "太太(已婚)", "sentence": "Mrs. Lee is my neighbor.", "sentence_cn": "李太太是我的鄰居。" },
{ "level": 5, "word": "Ms.", "syllables": ["Ms."], "ipa": "/mɪz/", "meaning": "女士(不論婚否)", "sentence": "Ms. Chen is a successful writer.", "sentence_cn": "陳女士是一位成功的作家。" },
{ "level": 5, "word": "nurse", "syllables": ["nurse"], "ipa": "/nɜːrs/", "meaning": "護士", "sentence": "The nurse takes care of the sick people.", "sentence_cn": "護士照顧生病的人。" },
{ "level": 5, "word": "parents", "syllables": ["par", "ents"], "ipa": "/ˈperənts/", "meaning": "父母親", "sentence": "I love my parents very much.", "sentence_cn": "我非常愛我的父母。" },
{ "level": 5, "word": "player", "syllables": ["play", "er"], "ipa": "/ˈpleɪər/", "meaning": "選手/球員", "sentence": "He is a famous basketball player.", "sentence_cn": "他是一位著名的籃球員。" },
{ "level": 5, "word": "police", "syllables": ["po", "lice"], "ipa": "/pəˈliːs/", "meaning": "警察", "sentence": "The police help keep our city safe.", "sentence_cn": "警察幫助維持城市的安全。" },
{ "level": 5, "word": "queen", "syllables": ["queen"], "ipa": "/kwiːn/", "meaning": "皇后", "sentence": "The queen wearing a golden crown.", "sentence_cn": "皇后戴著金色的皇冠。" },
{ "level": 5, "word": "singer", "syllables": ["sing", "er"], "ipa": "/ˈsɪŋər/", "meaning": "歌手", "sentence": "The singer has a beautiful voice.", "sentence_cn": "這位歌手有副好嗓子。" },
{ "level": 5, "word": "sister", "syllables": ["sis", "ter"], "ipa": "/ˈsɪstər/", "meaning": "姊妹", "sentence": "My little sister is five years old.", "sentence_cn": "我的小妹五歲了。" },
{ "level": 5, "word": "son", "syllables": ["son"], "ipa": "/sʌn/", "meaning": "兒子", "sentence": "Their son is a very smart boy.", "sentence_cn": "他們的兒子是個聰明的男孩。" },
{ "level": 5, "word": "student", "syllables": ["stu", "dent"], "ipa": "/ˈstuːdnt/", "meaning": "學生", "sentence": "The student is studying for the test.", "sentence_cn": "學生正在為考試讀書。" },
{ "level": 5, "word": "teacher", "syllables": ["teach", "er"], "ipa": "/ˈtiːtʃər/", "meaning": "老師", "sentence": "Our teacher is very patient with us.", "sentence_cn": "我們的老師對我們很有耐心。" },
{ "level": 5, "word": "woman", "syllables": ["wom", "an"], "ipa": "/ˈwʊmən/", "meaning": "女人", "sentence": "The woman is talking on the phone.", "sentence_cn": "那個女人正在講電話。" },
{ "level": 5, "word": "writer", "syllables": ["wri", "ter"], "ipa": "/ˈraɪtər/", "meaning": "作家", "sentence": "The writer wrote many famous books.", "sentence_cn": "這位作家寫過許多名著。" }
];